init_character_for_position("scarlit")

positions("scarlit", "active", "cowgirl",
    {
        "name": "bump grind and twerk",
        "flavor": "My mind's tellin' me no, but my booty, my booty's twerkin'",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "look back", "spank", "butt jiggle"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["couch"]
    },
    {
        "name": "fast and hard",
        "flavor": "It feels too good to stop now.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab butt", "spank", "look back"],
        "skill": "active sex",
        "skill level": 8,
        "locations": ["couch"]
    },
    {
        "name": "grinding and gyrating",
        "flavor": "You sensually grind and gyrate your hips into his.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 3,
        "roughness": 2,
        "your pleasure": 6,
        "pleasure factor": "length",
        "his pleasure": 5,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "grab boobs", "balance on chest", "romantic"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["bed"]
    },
    {
        "name": "impale yourself on BBC",
        "flavor": "It's so big compared to your tiny hole, there really isn't a better way to describe it.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "look back", "spank", "grab waist"],
        "skill": "active sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "pogo stick",
        "flavor": "Bouncing up and down like a pogo stick... if the pogo stick was big black cock.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 7,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "spank", "grab butt", "look back"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["couch"]
    },
    {
        "name": "rubbing and riding",
        "flavor": "He rubs your clit while you bounce up and down on that dick.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 3,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab waist"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["couch"]
    },
    {
        "name": "ruff ryder",
        "flavor": "Oh, no, that's how Ruff Ryders roll",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 9,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 10,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "spank", "grab waist", "look back"],
        "skill": "active sex",
        "skill level": 7,
        "locations": ["couch"]
    },
    {
        "name": "the best seat",
        "flavor": "You've got the best seat in the house. On his cock.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 4,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "balance on chest", "look back", "grab boobs", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["couch"]
    }
);

positions("scarlit", "active", "doggy",
    {
        "name": "it takes two",
        "flavor": "It takes two, baby, to make a dream come true, just takes two.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 7,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "look back", "spank"],
        "skill": "active sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "slide it back",
        "flavor": "Arch that back! Spread em and slide on back.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 3,
        "roughness": 6,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "spank", "grab butt"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["couch"]
    },
    {
        "name": "twerk on that cock",
        "flavor": "You try to spice it up a bit by twerkin while he pumps you.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 5,
        "roughness": 3,
        "your pleasure": 5,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "look back"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["couch"]
    }
);

positions("scarlit", "active", "service",
    {
        "name": "ball buffet",
        "flavor": "On tonight's menu... balls!",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 2,
        "roughness": 2,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "degrade", "eye contact"],
        "skill": "blowjob",
        "skill level": 6,
        "locations": ["bed", "couch"]
    },
    {
        "name": "coming up for air",
        "flavor": "You're either practicing to be a diver or giving really good head.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 4,
        "roughness": 2,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "blowjob", "close to crotch", "deepthroat"],
        "skill": "blowjob",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "sloppy 69",
        "flavor": "I made 'em extra sloppy for yous",
        "type": "active",
        "subtype": "service",
        "position": "69",
        "athletics": 6,
        "roughness": 3,
        "your pleasure": 8,
        "pleasure factor": "oral",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "sloppy", "pull hair", "blowjob"],
        "skill": "blowjob",
        "skill level": 6,
        "locations": ["bed", "couch"]
    },
    {
        "name": "standing 69",
        "flavor": "He flips you upside down, forcing his cock in your face, while he has himself a little snack.",
        "type": "active",
        "subtype": "service",
        "position": "69",
        "athletics": 8,
        "roughness": 6,
        "your pleasure": 7,
        "pleasure factor": "oral",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "standing", "69"],
        "skill": "blowjob",
        "skill level": 6,
        "locations": ["standing"]
    },
    {
        "name": "worship BBC",
        "flavor": "BBC is your new God. Worship it.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 4,
        "roughness": 3,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 7,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "blowjob", "close to crotch", "deepthroat"],
        "skill": "blowjob",
        "skill level": 4,
        "locations": ["couch"]
    }
);

positions("scarlit", "passive", "cowgirl",
    {
        "name": "full nelson",
        "flavor": "Held in place while he uses you.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "full nelson",
        "athletics": 8,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "nelson", "legs in the air", "helpless"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["couch"]
    },
    {
        "name": "legs up pounding",
        "flavor": "Lifting you up by your legs, he plows that pussy from below with his fat black cock.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "balls deep", "big thrusts"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["couch"]
    },
    {
        "name": "non-stop pounding",
        "flavor": "He just...won't...stop..",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 10,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "grab butt", "butt jiggle", "balls deep", "balls smacking"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed", "couch"]
    },
    {
        "name": "properly pounded",
        "flavor": "He's giving you a proper pounding.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "spank", "look back", "butt jiggle"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "rough yet intimate",
        "flavor": "The sex may be rough but it somehow feels romantic.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 6,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "pull hair", "balls smacking"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["couch"]
    },
    {
        "name": "suspended fuck",
        "flavor": "He easily lifts you up and sits you down on his cock.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "standing fuck",
        "athletics": 9,
        "roughness": 6,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "standing", "butt jiggle", "kiss"],
        "skill": "passive sex",
        "skill level": 8,
        "locations": ["standing"]
    },
    {
        "name": "suspended riding",
        "flavor": "He flips you around and lifts you up. Reverse cowgirl while suspended...Impressive.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "standing fuck",
        "athletics": 8,
        "roughness": 5,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "standing"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["standing"]
    }
);

positions("scarlit", "passive", "doggy",
    {
        "name": "all gas no brakes",
        "flavor": "There are no brakes on this train.",
        "type": "passive",
        "subtype": "doggy",
        "position": "side fuck",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "grab waist", "leg up"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "beat it up",
        "flavor": "Extra large and extra hard.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 9,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "look back", "balls smacking", "grab waist"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "cockhammering",
        "flavor": "Like jackhammering... except with his cock.",
        "type": "passive",
        "subtype": "doggy",
        "position": "side fuck",
        "athletics": 8,
        "roughness": 10,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 10,
        "his satisfaction": 10,
        "rhythm": 400,
        "tags": ["black", "grab head", "manhandled"],
        "skill": "passive sex",
        "skill level": 8,
        "locations": ["couch"]
    },
    {
        "name": "deep pound",
        "flavor": "He wraps both hands around your throat like a handle.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 5,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab neck", "butt jiggle", "look back"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "dominated by BBC",
        "flavor": "You're no match for him. He's absolutely dominating you.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 8,
        "roughness": 10,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 10,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "look back", "choke", "manhandled", "pull hair", "grab neck"],
        "skill": "passive sex",
        "skill level": 8,
        "locations": ["couch"]
    },
    {
        "name": "prone pounding",
        "flavor": "He pushed your head down and pulled your ass up towards him.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 4,
        "roughness": 3,
        "your pleasure": 5,
        "pleasure factor": "both",
        "his pleasure": 5,
        "his satisfaction": 5,
        "rhythm": 500,
        "tags": ["black", "ass up", "prone", "butt jiggle"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["couch"]
    },
    {
        "name": "sensual side fuck",
        "flavor": "He pulls you in close. Hitting all the right spots.",
        "type": "passive",
        "subtype": "doggy",
        "position": "side fuck",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "grab neck"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["bed"]
    },
    {
        "name": "spank me daddy",
        "flavor": "As the feelings overwhelm you, you start to spank yourself, showing him what to do.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 8,
        "roughness": 9,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "spank", "grab waist", "pull hair", "choke", "manhandled"],
        "skill": "passive sex",
        "skill level": 8,
        "locations": ["couch"]
    },
    {
        "name": "watch him fuck you",
        "flavor": "You're bent up in such a way that you actually get to watch him fuck your pussy. Front row tickets!",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 4,
        "roughness": 5,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "balls deep", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 2,
        "locations": ["couch"]
    },
    {
        "name": "wellness check",
        "flavor": "Between the noises coming out of your mouth and the slapping sounds, you may end up with the cops doing a wellness check.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 9,
        "roughness": 10,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 10,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "manhandled", "cover mouth", "choke", "balls deep"],
        "skill": "passive sex",
        "skill level": 9,
        "locations": ["couch"]
    }
);

positions("scarlit", "passive", "missionary",
    {
        "name": "all up in you",
        "flavor": "Oh wow, you can actually see him inside you...from the outside!",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "legs in the air", "grab sheets"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "cock pushups",
        "flavor": "You never know when you'll need to fuck your way out of a tight situation.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "eye contact", "balls deep"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "digging deep",
        "flavor": "Just because it's slow doesn't mean it's bad. He's really digging down deep this time.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 3,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "length",
        "his pleasure": 6,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "eye contact", "legs in the air"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["couch"]
    },
    {
        "name": "make you squirt",
        "flavor": "You just can't help yourself, it just kind of happens. He keeps hitting all the right spots. ",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 5,
        "roughness": 6,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "grab head"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "passionate missionary",
        "flavor": "You instinctively wrap your legs around him. You're his. All of you.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 2,
        "roughness": 2,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "romantic", "kiss", "legs in the air"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["bed"]
    },
    {
        "name": "s is for submission",
        "flavor": "You'll do anything he wants, you're such a good little pet.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "grab head", "boobs jiggle", "kiss"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "sidewinder",
        "flavor": "Even turned on your side, he still owns that pussy.",
        "type": "passive",
        "subtype": "missionary",
        "position": "side fuck",
        "athletics": 5,
        "roughness": 7,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "kiss", "eye contact", "spank"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "split open",
        "flavor": "Even you didn't know you were this good at taking dick.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "width",
        "his pleasure": 9,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "eye contact"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    }
);

positions("scarlit", "passive", "service",
    {
        "name": "finger blasted",
        "flavor": "Sometimes two fingers and some talent is all it takes.",
        "type": "passive",
        "subtype": "service",
        "position": "fingering",
        "athletics": 7,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "oral",
        "his pleasure": 0,
        "his satisfaction": 0,
        "rhythm": 500,
        "tags": ["black", "sloppy"],
        "skill": "orgasm control",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "pussy motorboat",
        "flavor": "It's not just eating pussy at this point. He's motorboatin that thing!",
        "type": "passive",
        "subtype": "service",
        "position": "cunnilingus",
        "athletics": 5,
        "roughness": 2,
        "your pleasure": 9,
        "pleasure factor": "oral",
        "his pleasure": 0,
        "his satisfaction": 0,
        "rhythm": 500,
        "tags": ["black", "sloppy"],
        "skill": "orgasm control",
        "skill level": 3,
        "locations": ["bed", "couch"]
    },
    {
        "name": "sit on his face",
        "flavor": "Even with you in this position, he is still somehow in control.",
        "type": "passive",
        "subtype": "service",
        "position": "cunnilingus",
        "athletics": 6,
        "roughness": 5,
        "your pleasure": 9,
        "pleasure factor": "oral",
        "his pleasure": 0,
        "his satisfaction": 0,
        "rhythm": 500,
        "tags": ["black", "sloppy", "boobs jiggle"],
        "skill": "orgasm control",
        "skill level": 7,
        "locations": ["couch"]
    }
);

