init_character_for_position("rae")

positions("rae", "passive", "service", 
    {
        "name": "facefuck",
        "flavor": "Your throat is his fleshlight.",
        "type": "passive",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 8,
        "roughness": 10,
        "your pleasure": 0,
        "pleasure factor": "oral",
        "his pleasure": 7,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "sloppy", "close to crotch", "deepthroat", "facefuck", "submissive", "helpless", "mandhandled", "drain"],
        "skill": "gag reflex",
        "skill level": 7,
        "locations": ["bed", "couch"]
    },
    {
        "name": "standing oral",
        "flavor": "He lifted you up like you were a feather.",
        "type": "passive",
        "subtype": "service",
        "position": "cunnilingus",
        "athletics": 9,
        "roughness": 4,
        "your pleasure": 8,
        "pleasure factor": "oral",
        "his pleasure": 0,
        "his satisfaction": 0,
        "rhythm": 500,
        "tags": ["black", "submissive", "helpless", "pussy licking", "ass up"],
        "skill": "orgasm control",
        "skill level": 5,
        "locations": ["standing"]
    },
    {
        "name": "spiderman",
        "flavor": "You don't get it. He told you it was from an old movie and it'd be hot.",
        "type": "passive",
        "subtype": "service",
        "position": "fingering",
        "athletics": 4,
        "roughness": 0,
        "your pleasure": 5,
        "pleasure factor": "oral",
        "his pleasure": 0,
        "his satisfaction": 0,
        "rhythm": 500,
        "tags": ["black", "fingering", "kiss"],
        "skill": "orgasm control",
        "skill level": 3,
        "locations": ["bed"]
      }
)
positions("rae", "active", "service",
      {
        "name": "girl you nasty",
        "flavor": "Aww, that's nasty.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 4,
        "roughness": 3,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "balls in face", "licking"],
        "skill": "handjob",
        "skill level": 6,
        "locations": ["bed"]
      }
)
positions("rae", "active", "missionary",
    {
        "name": "slow and sensual",
        "flavor": "Almost feels like prom night.",
        "type": "active",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 2,
        "roughness": 2,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 5,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "kiss", "balls deep", "romantic"],
        "skill": "active sex",
        "skill level": 2,
        "locations": ["bed", "couch"]
    },
    {
        "name": "passionate",
        "flavor": "He pulls you close, he's so deep.",
        "type": "active",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "kiss", "balls deep", "romantic", "eye contact"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["bed", "couch"]
    },
    {
        "name": "choke fuck",
        "flavor": "Having trouble breathing are we?",
        "type": "active",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "choke", "manhandled", "boobs jiggle", "eye contact"],
        "skill": "active sex",
        "skill level": 6,
        "locations": ["bed", "couch"]
    }
)
positions("rae", "passive", "missionary",
    {
        "name": "legs up squat",
        "flavor": "He holds you down while he impales you.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 5,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "balls deep", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed", "couch"]
    },
    {
        "name": "standing fuck",
        "flavor": "He's holding you up by your ass, as he slams into your pussy.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 9,
        "roughness": 9,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "butt view", "legs in the air", "balls deep", "manhandled", "grab butt", "standing fuck", "drain"],
        "skill": "passive sex",
        "skill level": 8,
        "locations": ["standing"]
    },
    {
        "name": "choke legs up",
        "flavor": "His hand around your neck, he pounds you mercilessly.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 7,
        "roughness": 9,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "balls deep", "manhandled", "boobs jiggle", "standing fuck"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["standing"]
    },
    {
        "name": "pinned and pounded",
        "flavor": "He has you pinned while he dicks you down.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 4,
        "roughness": 6,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "balls deep", "manhandled", "boobs jiggle", "mating press"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["standing"]
    },
    {
        "name": "deeper",
        "flavor": "So deep... he's so deep.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "balls deep", "kiss", "boobs jiggle", "mating press"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    },
    {
        "name": "chair fuck",
        "flavor": "Any surface will do.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "balls deep", "grab boobs", "grab head"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["chair"]
    }
)
positions("rae", "active", "cowgirl",
    {
        "name": "romantic riding",
        "flavor": "His hands on your hips, he guides you down onto his cock.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 2,
        "roughness": 4,
        "your pleasure": 6,
        "pleasure factor": "length",
        "his pleasure": 5,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "butt view", "romantic"],
        "skill": "active sex",
        "skill level": 2,
        "locations": ["bed", "couch"]
    },
    {
        "name": "pole rider",
        "flavor": "He holds you in place while he impales you.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 9,
        "your pleasure": 8,
        "pleasure factor": "length",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "manhandled", "balls smacking"],
        "skill": "active sex",
        "skill level": 7,
        "locations": ["bed", "couch"]
    },
    {
        "name": "cowgirl spanking",
        "flavor": "He slaps your ass while you ride him.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 7,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "spank", "look back"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    }
)
positions("rae", "passive", "cowgirl",
    {
        "name": "hair hold",
        "flavor": "He grabs your hair, holding you in place while he pounds you.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "butt view", "grab hair", "manhandled"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed", "couch"]
    },
    {
        "name": "walking on sunshine",
        "flavor": "... and it makes you feel good.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "grab waist", "balance with feet"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["bed", "couch"]
    }
)
positions("rae", "active", "doggy",
    {
        "name": "flamingo fuck",
        "flavor": "Balancing on one leg, he bends you over the couch.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 8,
        "roughness": 9,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "manhandled", "balls deep", "boobs jiggle","balls smacking","eye contact", "drain"],
        "skill": "active sex",
        "skill level": 7,
        "locations": ["couch"]
    }
)
positions("rae", "passive", "doggy",
    {
        "name": "fucktoy",
        "flavor": "Your name is now Fucktoy. You belong to him.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 10,
        "roughness": 10,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 10,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "manhandled", "grab hair", "grab waist", "balls smacking", "drain"],
        "skill": "passive sex",
        "skill level": 10,
        "locations": ["bed", "couch"]
    },
    {
        "name": "kitchen sink",
        "flavor": "He's throwing everything at you except the kitchen sink.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["standing"]
    },
    {
        "name": "podracing doggy",
        "flavor": "Now this is podracing?",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 7,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab waist", "balls deep"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "sidefuck",
        "flavor": "Is it supposed to feel this good?",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 4,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab waist", "balls deep", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["couch"]
    }
)
