init_character_for_position("jia")

positions("jia", "active", "cowgirl",
    {
        "name": "amateur riding",
        "flavor": "You're getting the hang of it, you think.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 3,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "eye contact", "legs spread"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["bed"]
    },
    {
        "name": "pole rider",
        "flavor": "His meat pole is splitting you in two, but you keep quaking that ass downward.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 7,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "spank", "butt jiggle"],
        "skill": "active sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "riding BBC",
        "flavor": "You impale yourself on BBC. Over and over again.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "romantic", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    },
    {
        "name": "slapped and choked",
        "flavor": "He's roughing you up while you ride that cock.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "choke", "spank", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 7,
        "locations": ["bed"]
    },
    {
        "name": "slow rider",
        "flavor": "Take it easy. Enjoy the ride.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 3,
        "roughness": 3,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "grab butt", "grab boobs", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["bed"]
    },
    {
        "name": "up close and personal",
        "flavor": "You lean in close as you ride him.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 5,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "wide stance",
        "flavor": "You take a wide stance, squatting down on that dick.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "kiss", "stablize", "boobs jiggle", "grab legs"],
        "skill": "active sex",
        "skill level": 7,
        "locations": ["bed"]
    }
)
positions("jia", "active", "doggy",
    {
        "name": "gyrating and grinding",
        "flavor": "You grind yourself back into him, gyrating those hips when they meet his.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 5,
        "roughness": 4,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "butt jiggle", "look back"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "rocking back",
        "flavor": "As he speeds up, you match his pace.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "butt jiggle", "grab waist"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["bed"]
    }
)
positions("jia", "active", "service",
    {
        "name": "ball worship",
        "flavor": "Suck the baby batter out of his balls.",
        "type": "active",
        "subtype": "service",
        "position": "handjob",
        "athletics": 3,
        "roughness": 3,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "eye contact", "sloppy", "lick balls"],
        "skill": "handjob",
        "skill level": 4,
        "locations": ["bed"]
      },
      {
        "name": "drooling blowjob",
        "flavor": "Drool runs out of your mouth, down onto your tits, as you slob on his knob.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 3,
        "roughness": 3,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "eye contact", "sloppy"],
        "skill": "blowjob",
        "skill level": 3,
        "locations": ["floor"]
      },
      {
        "name": "sloppy blowjob",
        "flavor": "Who needs lube when you have spit?",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 4,
        "roughness": 5,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "eye contact", "sloppy", "spit"],
        "skill": "blowjob",
        "skill level": 5,
        "locations": ["bed"]
      },
      {
        "name": "smearing your lipstick",
        "flavor": "He's ruining your favorite shade.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "eye contact"],
        "skill": "blowjob",
        "skill level": 6,
        "locations": ["floor"]
      },
      {
        "name": "worship BBC",
        "flavor": "BBC is your new God. Worship it.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 5,
        "roughness": 5,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "eye contact", "sloppy"],
        "skill": "blowjob",
        "skill level": 5,
        "locations": ["bed", "couch"]
      }
)
positions("jia", "passive", "cowgirl",
    {
        "name": "more than a handful",
        "flavor": "He grabs a handful of your ass, and then some.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab butt", "boobs jiggle", "spank"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["bed", "couch"]
    },
    {
        "name": "overstimulated",
        "flavor": "He's sucking on your tit, squeezing your ass, and fucking you all at once.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab butt", "butt jiggle"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "pounded from below",
        "flavor": "He's really going to town on you.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 9,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "grab waist", "boobs jiggle", "eye contact", "spank", "manhandled"],
        "skill": "passive sex",
        "skill level": 8,
        "locations": ["bed"]
    },
    {
        "name": "pulled close",
        "flavor": "He pulls you close while he thrusts into you.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 6,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab butt", "spank"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "rough rodeo",
        "flavor": "Squatting down, he holds you in place, his balls slapping off your ass with each thrust.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab waist", "butt jiggle", "balls deep", "squat"],
        "skill": "passive sex",
        "skill level": 8,
        "locations": ["bed"]
    },
    {
        "name": "suspended cowgirl",
        "flavor": "He lifts you up and pulls you close.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 9,
        "roughness": 6,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "kiss", "legs in air"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["bed", "couch"]
    }
)
positions("jia", "passive", "doggy",
    {
        "name": "bottoming out",
        "flavor": "It's not even all the way in and he's scraping bottom.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab waist", "butt jiggle", "look back"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "face down ass up",
        "flavor": "It's all about finding the right angle.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 4,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "spank", "butt jiggle", "grab waist", "look back"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "fucked silly",
        "flavor": "Your eyes roll back into your head as he fucks you silly.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "push down", "butt jiggle", "grab waist", "eyes rolling"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "manhandled",
        "flavor": "You're just a toy for him to play with.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 7,
        "roughness": 9,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 10,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "butt jiggle", "manhandled", "grab hair", "grab neck"],
        "skill": "passive sex",
        "skill level": 9,
        "locations": ["bed"]
    },
    {
        "name": "on all fours",
        "flavor": "In the true essence of doggystyle, your bent down on all fours, while he rams you.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 4,
        "roughness": 6,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "spank", "grab butt", "all fours"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "so deep",
        "flavor": "He's shoving it all the way inside.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab neck", "butt jiggle", "look back", "kiss", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "plowed doggy",
        "flavor": "Better find something to bite down on, because he's straight plowing that pussy.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 9,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 10,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "balls deep", "butt jiggle", "eyes rolling", "push down"],
        "skill": "passive sex",
        "skill level": 9,
        "locations": ["bed"]
    },
    {
        "name": "roughly fucked",
        "flavor": "He holds you down and fucks you proper.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab waist", "butt jiggle", "push down"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["bed"]
    },
    {
        "name": "spread em",
        "flavor": "Help him out, spread those cheeks apart.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 7,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "grab waist", "butt jiggle"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["bed"]
    },
    {
        "name": "wiggle that jiggly booty",
        "flavor": "Shake what your mama gave ya... on his dick.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 8,
        "roughness": 4,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "spank", "butt jiggle"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    }
)
positions("jia", "passive", "missionary",
    {
        "name": "leg press",
        "flavor": "He presses down into your leg, keeping it airborne.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "eye contact", "grab leg", "leg up", "eyes rolling"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed", "couch"]
    },
    {
        "name": "medium missionary",
        "flavor": "You can do more than just lay there. So you lean up, slightly.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "eye contact", "grab head", "leg up"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["bed", "couch"]
    },
    {
        "name": "one leg held up",
        "flavor": "He holds up your leg so you can rub your clit.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "eye contact", "grab leg", "leg up"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed", "couch"]
    },
    {
        "name": "plowed",
        "flavor": "You rub yourself while he plows that pussy.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "eye contact", "legs in the air"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["bed", "couch"]
    },
    {
        "name": "pounded",
        "flavor": "He's pounding that pussy.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 5,
        "roughness": 7,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "legs in the air"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "powerful missionary",
        "flavor": "He's so strong...",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 7,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "romantic", "grab head", "legs in the air"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["bed"]
    },
    {
        "name": "slow and sensual",
        "flavor": "When he slows down, you can feel every detail.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 5,
        "roughness": 3,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "eye contact", "kiss", "leg up"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["bed", "couch"]
    },
    {
        "name": "toe curling pleasure",
        "flavor": "He's hitting all the right spots.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "kiss", "grab head", "legs in the air"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    }
)
positions("jia", "passive", "service",
    {
        "name": "finger blasted",
        "flavor": "So anyway, he started blastin your pussy with his finger guns.",
        "type": "passive",
        "subtype": "service",
        "position": "fingering",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "oral",
        "his pleasure": 0,
        "his satisfaction": 0,
        "rhythm": 500,
        "tags": ["black", "fingering", "eye contact"],
        "skill": "orgasm control",
        "skill level": 5,
        "locations": ["bed"]
      }
)
