init_character_for_position("alina")

positions("alina", "active", "cowgirl",
    {
        "name": "chocolate banana split",
        "flavor": "Is this dessert or a position name? Why not both.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 8,
        "roughness": 3,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "look back", "legs spread", "butt jiggle"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "expert riding",
        "flavor": "You're a pro. You know all the right angles, the rhythm, everything.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 10,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "eyes roll", "spank", "butt jiggle", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 8,
        "locations": ["bed", "couch"]
    },
    {
        "name": "medium riding",
        "flavor": "You're getting there. Sure it feels good, but you've got some room to learn.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "look back"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    },
    {
        "name": "pleasure overload",
        "flavor": "It feels too good, you just can't take it.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "eyes roll",  "boobs jiggle", "grab boobs"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["couch", "bed"]
    },
    {
        "name": "pogo stick",
        "flavor": "Ridin' that dick like a pogo stick.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 7,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "look back", "butt jiggle", "spank"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "reverse riding",
        "flavor": "Lean back and take that cock for a spin.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "grab waist"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["couch"]
    },
    {
        "name": "ruff rider",
        "flavor": "You just can't help yourself from riding hard on his cock.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 7,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "look back", "grab butt", "spank", "butt jiggle"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "slam it in",
        "flavor": "You keep slamming your tight ass down on top of his BBC.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "grab waist"],
        "skill": "active sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "wide stance",
        "flavor": "With a wider stance, it just hits better angles. At least, that's what you tell yourself.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 4,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "legs spread"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["bed"]
    }
)
positions("alina", "active", "doggy",
    {
        "name": "getting some help",
        "flavor": "You're setting the pace, but he's quickening it.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 3,
        "roughness": 4,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "butt jiggle", "look back", "grab butt"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["bed"]
    },
    {
        "name": "kick his ass",
        "flavor": "Drive him into your pussy with your feet.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 7,
        "roughness": 4,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "butt jiggle", "look back"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["bed","couch"]
    },
    {
        "name": "learning to twerk",
        "flavor": "With a little more effort, it might look like you know how to twerk.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 3,
        "roughness": 2,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "butt jiggle", "look back", "spank"],
        "skill": "active sex",
        "skill level": 2,
        "locations": ["couch"]
    },
    {
        "name": "slide on down",
        "flavor": "Go on and slide that tight ass down until he's all the way in.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "butt jiggle", "look back"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["bed","couch"]
    },
    {
        "name": "throw that ass back",
        "flavor": "When he tells you to 'throw that ass back', it means he wants to hear your ass clap against him. ",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 5,
        "roughness": 5,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "balls deep", "butt jiggle", "look back", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["couch"]
    }
)
positions("alina", "active", "missionary",
    {
        "name": "a standing ovation",
        "flavor": "As if a standing fuck wasn't hard enough, he tossed your leg over his shoulder and told you start riding.",
        "type": "active",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 9,
        "roughness": 5,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "standing", "balls deep", "eye contact", "butt jiggle"],
        "skill": "active sex",
        "skill level": 7,
        "locations": ["standing"]
    }
)
positions("alina", "active", "service",
    {
        "name": "cock and ball worship",
        "flavor": "Don't neglect the balls during your worship session.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 3,
        "roughness": 3,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "eye contact", "sloppy", "lick balls"],
        "skill": "blowjob",
        "skill level": 4,
        "locations": ["bed","couch"]
      },
      {
        "name": "full service station",
        "flavor": "Not just the cock and balls but, the full service.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 3,
        "roughness": 3,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "eye contact", "sloppy", "lick balls"],
        "skill": "blowjob",
        "skill level": 5,
        "locations": ["bed"]
      },
      {
        "name": "stretching your throat",
        "flavor": "How does it even fit in your mouth?",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 4,
        "roughness": 5,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "eye contact", "sloppy"],
        "skill": "blowjob",
        "skill level": 4,
        "locations": ["bed"]
      },
      {
        "name": "supergirl",
        "flavor": "Able to suck tall cocks in a single bound.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 9,
        "roughness": 3,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "eye contact", "sloppy"],
        "skill": "blowjob",
        "skill level": 6,
        "locations": ["bed","couch"]
      },
      {
        "name": "train your gag reflex",
        "flavor": "How far down can you get it?",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "eye contact", "sloppy"],
        "skill": "blowjob",
        "skill level": 3,
        "locations": ["couch"]
      },
      {
        "name": "two handed blowjob",
        "flavor": "Sometimes it just takes both hands.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "eye contact", "sloppy"],
        "skill": "blowjob",
        "skill level": 4,
        "locations": ["couch"]
      },
      {
        "name": "worship BBC",
        "flavor": "BBC is your new God. Worship it.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 4,
        "roughness": 6,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 10,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "eye contact", "sloppy"],
        "skill": "blowjob",
        "skill level": 4,
        "locations": ["floor"]
      }
      
)
positions("alina", "passive", "cowgirl",
    {
        "name": "deep thrusts",
        "flavor": "You didn't know it could go this deep.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab waist", "balls deep", "big thrusts"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed","couch"]
    },
    {
        "name": "drilled",
        "flavor": "He holds you up and drills you from below.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 5,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab butt", "butt jiggle", "look back"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["couch"]
    },
    {
        "name": "getting a butt lift",
        "flavor": "Is this what they meant by getting a butt lift?",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab butt", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["bed"]
    },
    {
        "name": "intense pumping",
        "flavor": "He's pumping you... intensely. That's the entire flavor text.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 8,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab waist", "butt jiggle", "look back"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed","couch"]
    },
    {
        "name": "morse code",
        "flavor": "It's like he's sending an encoded message with your butt jiggles.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 3,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab butt", "butt jiggle"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "pounded from below",
        "flavor": "Nothing fancy, he's just pounding you... from below.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 3,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "grab waist", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["couch"]
    },
    {
        "name": "paul bunyon",
        "flavor": "Man thinks he's splitting wood with how he's hacking away at your needy cunt.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "grab legs", "butt jiggle", "look back", "spank"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["couch"]
    },
    {
        "name": "splitting you open",
        "flavor": "I don't know what possessed you to show off your flexibility, but he's really taking advantage of your vulnerability.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 10,
        "roughness": 10,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 10,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "balls smacking", "butt jiggle", "balls deep"],
        "skill": "passive sex",
        "skill level": 9,
        "locations": ["couch"]
    },
    {
        "name": "standing from behind",
        "flavor": "He lifts you into the air, from behind, and sets you down on his cock.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 9,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab legs", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["standing"]
    },
    {
        "name": "standing ride",
        "flavor": "He pins your against the wall and lifts you onto his cock.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab butt", "boobs jiggle", "eye contact"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["standing"]
    }
)
positions("alina", "passive", "doggy",
    {
        "name": "cock pushups",
        "flavor": "You never know when you'll need to fuck your way out of a tight situation.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 9,
        "roughness": 6,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "butt jiggle", "all fours"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "doing some work",
        "flavor": "Whatever he's doing back there, it's working.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 4,
        "roughness": 6,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "pull hair", "butt jiggle", "eye contact", "spank"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "drilling for oil",
        "flavor": "He's certainly drilling, but I don't think it's for oil...",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 3,
        "roughness": 6,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "butt view"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["bed"]
    },
    {
        "name": "firmly flattened",
        "flavor": "You feel his weight on top of you, holding you firmly in place.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 5,
        "roughness": 7,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "eyes roll", "butt jiggle", "look back"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["couch"]
    },
    {
        "name": "fucked stupid",
        "flavor": "Your eyes roll back into your head, again and again... I think you're losing brain cells.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 7,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab waist", "butt jiggle", "eyes roll"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch","bed"]
    },
    {
        "name": "grippin that dick",
        "flavor": "Your pussy ain't lettin go of that BBC.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "grab butt", "boobs jiggle", "look back"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "plowed by BBC",
        "flavor": "You grab whatever you can reach while he absolutely plows you with his BBC.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 10,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "big thrusts", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["bed"]
    },
    {
        "name": "shut up already",
        "flavor": "He's tired of hearing you complain, he shoves your face into the bed and keeps pounding you.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 8,
        "roughness": 10,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab head", "butt jiggle", "eyes roll"],
        "skill": "passive sex",
        "skill level": 8,
        "locations": ["bed"]
    },
    {
        "name": "sideways from behind",
        "flavor": "I guess he had something else in mind when you asked for Blockbuster and Chill.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 3,
        "roughness": 3,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "look back"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    }
)
positions("alina", "passive", "missionary",
    {
        "name": "all the way in",
        "flavor": "Further and further with each push, until it's all the way in.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "grab head", "legs spread", "balls deep"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["couch"]
    },
    {
        "name": "ankle necklace",
        "flavor": "His favorite piece of jewelry is your ankles as a necklace.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "balls deep", "legs spread"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "fuck you so good",
        "flavor": "Oh sweetie, he's fucking you so good. So much better than *you* ever did when you were a man",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "eye contact", "legs spread"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "love makin",
        "flavor": "Sometimes sex is just fucking. Other times, you feel like makin' love.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "eyes roll", "romantic", "legs spread", "balls deep"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "on the counter",
        "flavor": "It wasn't me.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 4,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "grab boobs", "legs spread"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["table"]
    },
    {
        "name": "self spread",
        "flavor": "You spread your own legs open for him.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "eye contact", "eyes roll", "legs spread", "grab boobs"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["couch"]
    },
    {
        "name": "side angle",
        "flavor": "He flips one leg over the order, holding you sideways.",
        "type": "passive",
        "subtype": "missionary",
        "position": "side fuck",
        "athletics": 5,
        "roughness": 4,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "grab leg", "leg up", "side fuck"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["couch"]
    },
    {
        "name": "spread eagle",
        "flavor": "He holds your legs up, spread open.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eyes roll", "grab legs", "legs spread", "balls deep"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["couch"]
    },
    {
        "name": "stretching you out",
        "flavor": "Your pussy grips his dick the entire way in. It's so tight... how can he possible be this thick?",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 5,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "big thrusts", "legs in the air", "balls deep"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed"]
    }
)
positions("alina", "passive", "service",
    {
        "name": "coming up for air",
        "flavor": "You cough and sputter in between his thrusts.",
        "type": "passive",
        "subtype": "service",
        "position": "facefuck",
        "athletics": 6,
        "roughness": 9,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "sloppy", "close to crotch", "deepthroat", "facefuck", "manhandled"],
        "skill": "gag reflex",
        "skill level": 7,
        "locations": ["couch"]
    },
    {
        "name": "facefuck 69",
        "flavor": "He holds your face in place, fucks it, and eats you out. Quite the talented multi-tasker.",
        "type": "passive",
        "subtype": "service",
        "position": "facefuck",
        "athletics": 7,
        "roughness": 9,
        "your pleasure": 9,
        "pleasure factor": "oral",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "sloppy", "close to crotch", "deepthroat", "facefuck", "helpless"],
        "skill": "gag reflex",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "gluck gluck gluck",
        "flavor": "The only sound that manages to come out of your mouth.",
        "type": "passive",
        "subtype": "service",
        "position": "facefuck",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "sloppy", "close to crotch", "deepthroat", "facefuck", "manhandled"],
        "skill": "gag reflex",
        "skill level": 7,
        "locations": ["couch"]
    },
    {
        "name": "sit on his face",
        "flavor": "He holds you confidently in place while he grabs a bite.",
        "type": "passive",
        "subtype": "service",
        "position": "cunnilingus",
        "athletics": 6,
        "roughness": 3,
        "your pleasure": 8,
        "pleasure factor": "oral",
        "his pleasure": 0,
        "his satisfaction": 0,
        "rhythm": 500,
        "tags": ["black", "pussy licking"],
        "skill": "orgasm control",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "split on his face",
        "flavor": "Well now you're just showing off...",
        "type": "passive",
        "subtype": "service",
        "position": "cunnilingus",
        "athletics": 10,
        "roughness": 3,
        "your pleasure": 10,
        "pleasure factor": "oral",
        "his pleasure": 0,
        "his satisfaction": 0,
        "rhythm": 500,
        "tags": ["black", "pussy licking"],
        "skill": "orgasm control",
        "skill level": 8,
        "locations": ["couch"]
    },
    {
        "name": "the balls too",
        "flavor": "Don't forget to cup the balls.",
        "type": "passive",
        "subtype": "service",
        "position": "facefuck",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "sloppy", "close to crotch", "deepthroat", "facefuck", "balls in face"],
        "skill": "gag reflex",
        "skill level": 7,
        "locations": ["couch"]
    }
)
