init_character_for_position("mia")

positions("mia", "active", "cowgirl",
    {
        "name": "grind into him",
        "flavor": "Your hips dig into his as you ride and grind.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 3,
        "roughness": 2,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "eye contact", "grab butt", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["bed", "couch"]
    },
    {
        "name": "move your feet lose your seat",
        "flavor": "Keep your balance while he pounds you from beneath.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "balance with feet", "grab waist", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    },
    {
        "name": "not your first rodeo",
        "flavor": "You leverage your experience, you know what he likes.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 6,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "tits against him", "grab butt", "butt jiggle"],
        "skill": "active sex",
        "skill level": 7,
        "locations": ["bed"]
    },
    {
        "name": "shaft rider",
        "flavor": "Leaning back, you watch his long black shaft glisten with your pussy juices.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab waist", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "slamming down on BBC",
        "flavor": "You mount the stallion, slamming yourself down on his BBC.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 7,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "mount", "butt jiggle", "spank"],
        "skill": "active sex",
        "skill level": 7,
        "locations": ["bed"]
    },
    {
        "name": "tits in his face",
        "flavor": "Your tits swing in front of his face while you ride him. He can't help himself to a taste.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 5,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "tits in face", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["bed"]
    }
)
positions("mia", "active", "doggy",
    {
        "name": "back it up",
        "flavor": "Girl, you looks good, won't you back that azz up.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 5,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "butt jiggle", "all fours", "look back"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "bounce back",
        "flavor": "Bounce that booty while you slide back onto his cock.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "butt jiggle", "all fours", "look back"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "cock sleeve",
        "flavor": "Grab his dick, make a sleeve for his cock to go through before it enters you.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 5,
        "roughness": 3,
        "your pleasure": 5,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "grab butt", "look back"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "take a seat",
        "flavor": "The best seat in the house, his cock.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 5,
        "roughness": 4,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "butt jiggle", "all fours"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["bed", "couch"]
    }
)
positions("mia", "active", "missionary",
    {
        "name": "standing leg up",
        "flavor": "He holds your leg up and plows you.",
        "type": "active",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 8,
        "roughness": 3,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "grab butt", "kiss", "standing", "leg up"],
        "skill": "active sex",
        "skill level": 6,
        "locations": ["standing"]
    }
)
positions("mia", "active", "service",
    {
        "name": "cock feeding",
        "flavor": "If you're good enough, maybe something NUTritious will come out.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "eye contact", "sloppy"],
        "skill": "blowjob",
        "skill level": 6,
        "locations": ["bed", "couch"]
      },
      {
        "name": "flexible 69",
        "flavor": "Always make sure to stretch before strenuous activity. Or maybe during.",
        "type": "active",
        "subtype": "service",
        "position": "69",
        "athletics": 10,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "oral",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "69", "licking"],
        "skill": "blowjob",
        "skill level": 8,
        "locations": ["bed", "couch"]
      },
      {
        "name": "tittyfuck",
        "flavor": "Jerk off that cock with your fun bags.",
        "type": "active",
        "subtype": "service",
        "position": "titfuck",
        "athletics": 5,
        "roughness": 2,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "titfuck", "close to crotch", "jerking"],
        "skill": "titfuck",
        "skill level": 4,
        "locations": ["bed", "couch"]
      },
      {
        "name": "worship BBC",
        "flavor": "BBC is your new God. Worship it.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 4,
        "roughness": 3,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "blowjob", "jerking"],
        "skill": "blowjob",
        "skill level": 3,
        "locations": ["bed", "couch"]
      }
)
positions("mia", "passive", "cowgirl",
    {
        "name": "laid back pumping",
        "flavor": "Both in posture and attitude, he casually pumps you.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 3,
        "roughness": 3,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "grab waist", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["bed"]
    },
    {
        "name": "laying pipe",
        "flavor": "Did somebody call a plumber?",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab boobs", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "legs in the air",
        "flavor": "He holds your legs up in the air while he pounds you.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "grab boobs", "legs together"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "rubbing and pumping",
        "flavor": "Rub that clit while he pumps your pussy.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "grab boobs", "legs together"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["bed"]
    },
    {
        "name": "standing ride",
        "flavor": "He holds you up by your ass while he plows you.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "missionary",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "manhandled", "grab butt", "legs in the air"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["standing"]
    }
)
positions("mia", "passive", "doggy",
    {
        "name": "bootylicious",
        "flavor": "With your ASSets on display, he can't help but smack them.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "spank", "butt jiggle"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "cock pushups",
        "flavor": "You never know when you'll need to fuck your way out of a tight situation.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 8,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "spank", "grab waist"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed", "floor"]
    },
    {
        "name": "face down ass up",
        "flavor": "Arch your back more. Show him where you belong.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "look back", "butt jiggle"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "just take it",
        "flavor": "You don't get a choice, you're stuck until he's finished with you.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab hair", "butt jiggle", "manhandled"],
        "skill": "passive sex",
        "skill level": 8,
        "locations": ["bed"]
    },
    {
        "name": "leg up doggy",
        "flavor": "Kick your leg up so he can fuck you better.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "spank", "butt jiggle", "look back"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed", "couch"]
    },
    {
        "name": "personal plaything",
        "flavor": "You've become his personal plaything. He gets to use you however he likes.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 7,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "manhandled", "boobs jiggle", "grab waist"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["bed", "couch"]
    },
    {
        "name": "plowed",
        "flavor": "He holds you in place while he plows you.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 4,
        "roughness": 7,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "spank", "butt jiggle", "grab butt", "manhandled"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["bed", "couch"]
    },
    {
        "name": "puppy love",
        "flavor": "Sometimes it's not fucking, it's making love.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 3,
        "roughness": 3,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "kiss", "romantic", "all fours"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["bed", "couch"]
    },
    {
        "name": "rough self spank",
        "flavor": "Spank yourself, so he doesn't have to.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 5,
        "roughness": 7,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "grab waist", "look back"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed", "couch"]
    },
    {
        "name": "roughed up",
        "flavor": "With a handful of your hair, he roughs up that ass with his free hand.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "grab hair", "spank", "manhandled"],
        "skill": "passive sex",
        "skill level": 8,
        "locations": ["bed", "couch"]
    },
    {
        "name": "sidewinder",
        "flavor": "Go ahead, lay on your side, take a break... he's going to keep going though.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 4,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "eye contact", "legs together", "side fuck"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    },
    {
        "name": "up close and personal",
        "flavor": "He fucks you so good, it produced an eyeliner tear trail.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 9,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "grab hair", "titty clap", "manhandled", "all fours"],
        "skill": "passive sex",
        "skill level": 8,
        "locations": ["bed", "couch"]
    },
    {
        "name": "watch him fuck you",
        "flavor": "Kick up a leg and watch him fuck you.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 5,
        "roughness": 3,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "eye contact"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed", "couch"]
    }
)
positions("mia", "passive", "missionary",
    {
        "name": "leg up missionary",
        "flavor": "Holding your up leg up in the air, so he can fuck you better.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "eye contact", "grab head", "leg up"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed", "couch"]
    },
    {
        "name": "long and deep",
        "flavor": "It's so long... are you truly bottomless?",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 7,
        "your pleasure": 8,
        "pleasure factor": "length",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "holding legs apart", "legs in the air"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "pouncing on prey",
        "flavor": "Like a lion, pouncing on its prey.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 5,
        "roughness": 5,
        "your pleasure": 8,
        "pleasure factor": "length",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "legs in the air"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "pretzel",
        "flavor": "He's tired of holding your leg, hold it yourself.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 7,
        "roughness": 5,
        "your pleasure": 8,
        "pleasure factor": "length",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "leg up", "grab shoulder"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "shaky leg",
        "flavor": "I stick my leg out on the flo' and start jiggin'.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "length",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "leg up"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "skewered",
        "flavor": "He skewers that pussy with his dick.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 5,
        "your pleasure": 9,
        "pleasure factor": "length",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "leg up", "eye contact"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    }
)
positions("mia", "passive", "service",
    {
        "name": "throat fleshlight",
        "flavor": "Enough talking. Your throat is now a fleshlight.",
        "type": "passive",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 8,
        "roughness": 9,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "sloppy", "close to crotch", "deepthroat", "facefuck", "helpless"],
        "skill": "gag reflex",
        "skill level": 8,
        "locations": ["floor"]
    },
    {
        "name": "titfuck n ballsuck",
        "flavor": "You can't help but suck his balls as he uses your tit pussy.",
        "type": "passive",
        "subtype": "service",
        "position": "titfuck",
        "athletics": 5,
        "roughness": 4,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "titfuck", "close to crotch"],
        "skill": "titfuck",
        "skill level": 4,
        "locations": ["bed", "couch"]
      },
      {
        "name": "choked and rubbed",
        "flavor": "One hand around your neck, the other rubs your clit.",
        "type": "passive",
        "subtype": "service",
        "position": "fingering",
        "athletics": 5,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "oral",
        "his pleasure": 0,
        "his satisfaction": 0,
        "rhythm": 500,
        "tags": ["black", "fingering", "close to crotch"],
        "skill": "orgasm control",
        "skill level": 4,
        "locations": ["bed", "couch"]
      }
)
