init_character_for_position("lana")

positions("lana", "active", "cowgirl",
    {
        "name": "bouncing bubble butt",
        "flavor": "Your tight bubble butt bounces up and down onto his cock.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "butt view", "grab butt", "butt jiggle"],
        "skill": "active sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "bouncing on BBC",
        "flavor": "Brace yourself and bounce up and down on that BBC.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 4,
        "your pleasure": 5,
        "pleasure factor": "both",
        "his pleasure": 5,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "butt view", "butt jiggle"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["bed", "couch"]
    },
    {
        "name": "bucking bronco",
        "flavor": "Toss yourself back, slam your hips into his.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 7,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "butt view", "boobs jiggle", "hair swish"],
        "skill": "active sex",
        "skill level": 6,
        "locations": ["bed", "couch"]
    },
    {
        "name": "keep your balance",
        "flavor": "Balance yourself on his legs while he pounds you.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 8,
        "roughness": 7,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "balance with feet", "grab waist"],
        "skill": "active sex",
        "skill level": 6,
        "locations": ["bed", "couch"]
    },
    {
        "name": "nympho impaling",
        "flavor": "Impale yourself on his cock like some kind of crazy nympho.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 9,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "butt view", "boobs jiggle", "hair swish", "spank", "grab ass"],
        "skill": "active sex",
        "skill level": 8,
        "locations": ["bed", "couch"]
    },
    {
        "name": "reverse cowgirl",
        "flavor": "You don't need to see him to know he likes it.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "grab waist"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["bed", "couch"]
    },
    {
        "name": "rocking and rolling",
        "flavor": "Roll those hips and rock into him.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 2,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 5,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["bed", "couch"]
    },
    {
        "name": "squatting rodeo",
        "flavor": "Bracing yourself on his legs, you squat down on his dick.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "length",
        "his pleasure": 6,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "squat"],
        "skill": "active sex",
        "skill level": 6,
        "locations": ["bed", "couch"]
    },
    {
        "name": "twerk on that dick",
        "flavor": "Twerk that bubble butt down onto his dick.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    },
    {
        "name": "wiggle and ride",
        "flavor": "wiggle that cute butt while you ride his cock.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["bed", "couch"]
    }
)
positions("lana", "active", "doggy",
    {
        "name": "sliding back",
        "flavor": "You slide that bubble butt back onto his pole.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "balls deep", "boobs jiggle", "butt jiggle", "all fours", "look back"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["couch"]
    }
)
positions("lana", "active", "service",
    {
        "name": "balls in mouth",
        "flavor": "Lick on those chocolate salty balls.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 3,
        "roughness": 2,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "balls in face", "licking"],
        "skill": "blowjob",
        "skill level": 4,
        "locations": ["bed"]
      },
      {
        "name": "gluck gluck gluck",
        "flavor": "The only sound that manages to come out of your mouth.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 5,
        "roughness": 6,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "sloppy"],
        "skill": "blowjob",
        "skill level": 6,
        "locations": ["bed", "couch"]
      },
      {
        "name": "just the tip",
        "flavor": "All you can fit in is the tip. But you still try...",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 5,
        "roughness": 3,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 4,
        "his satisfaction": 3,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "licking"],
        "skill": "blowjob",
        "skill level": 2,
        "locations": ["bed", "couch"]
      },
      {
        "name": "make out with his cock",
        "flavor": "Like a lover's tongue, you make out with his cock.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 3,
        "roughness": 2,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 5,
        "his satisfaction": 4,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "licking"],
        "skill": "blowjob",
        "skill level": 3,
        "locations": ["bed", "couch"]
      },
      {
        "name": "worship that BBC",
        "flavor": "BBC is your new God. Worship it.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 5,
        "roughness": 4,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 6,
        "his satisfaction": 5,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "licking", "sloppy"],
        "skill": "blowjob",
        "skill level": 5,
        "locations": ["bed", "couch"]
      }
)
positions("lana", "passive", "cowgirl",
    {
        "name": "BBC butt lift",
        "flavor": "Lift and hold... those cheeks open for BBC.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "butt view", "grab butt", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed", "couch"]
    },
    {
        "name": "front row seat",
        "flavor": "You've got the best seat in the house, to watch him fuck you.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 3,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "grab waist", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    },
    {
        "name": "legs up",
        "flavor": "Holding your legs up, he drills into you.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 3,
        "your pleasure": 5,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "grab legs", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["couch"]
    },
    {
        "name": "passionate pounding",
        "flavor": "He holds you close while he pounds your pussy.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "grab butt", "butt jiggle"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    },
    {
        "name": "plap plap plap",
        "flavor": "The sound of your asscheeks clapping off his thighs as he pounds you.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab waist", "butt jiggle"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["bed", "couch"]
    },
    {
        "name": "rough butt romantic",
        "flavor": "He's rough, with your butt...but in a romantic way.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 8,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab butt", "butt jiggle", "spank", "manhandled"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed", "couch"]
    },
    {
        "name": "sexy saddle",
        "flavor": "You look so sexy when you saddle up and ride that dick.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 7,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab butt", "butt jiggle", "eye contact"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "slow and deep",
        "flavor": "Take it slow, feel every inch.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 2,
        "roughness": 2,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 5,
        "his satisfaction": 5,
        "rhythm": 500,
        "tags": ["black", "grab butt", "butt jiggle"],
        "skill": "passive sex",
        "skill level": 2,
        "locations": ["bed", "couch"]
    }
)
positions("lana", "passive", "doggy",
    {
        "name": "bite the bullet",
        "flavor": "Bite down on something and just take it",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 4,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab butt", "balls deep", "eye contact"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "deep dark desires",
        "flavor": "Your desires, like the alpha man on top of you, are dark... and deep inside of you.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 3,
        "roughness": 5,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "balls deep", "eyes rolling"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["bed"]
    },
    {
        "name": "face down",
        "flavor": "You don't need to see him, he's going to plow you regardless.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 2,
        "roughness": 6,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "balls deep", "butt jiggle"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "flexible fuck",
        "flavor": "Don't forget to stretch.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 8,
        "roughness": 5,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "grab waist", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["bed"]
    },
    {
        "name": "one leg up",
        "flavor": "One of your legs gets held up while you get railed.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "grab boobs", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed", "couch"]
    },
    {
        "name": "standing doggy",
        "flavor": "You wrap your arm around him for leverage while he wrecks that pussy.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "eye contact", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 8,
        "locations": ["standing"]
    }
)
positions("lana", "passive", "missionary",
    {
        "name": "actual fingerfucking",
        "flavor": "He slides a few fingers into your pussy... as he's fucking it!",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "eye contact", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed", "couch"]
    },
    {
        "name": "fuck the orgasm out of you",
        "flavor": "He's going low and deep so you can rub one out.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 5,
        "roughness": 5,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed", "couch"]
    },
    {
        "name": "fucked and rubbed",
        "flavor": "He rubs your clit while he pounds you.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 5,
        "roughness": 6,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "eye contact", "boobs jiggle", "legs in the air"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    },
    {
        "name": "leg press",
        "flavor": "He pins you down by your thighs while he pumps you.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "legs in the air"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed", "couch"]
    },
    {
        "name": "leg up sideways",
        "flavor": "You hold your leg up while he fucks you sideways.",
        "type": "passive",
        "subtype": "missionary",
        "position": "side fuck",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "legs in the air", "eye contact", "grab tits", "side fuck"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    },
    {
        "name": "legs up ass slap",
        "flavor": "He holds your legs up and slaps your ass.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 7,
        "roughness": 7,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "legs in the air", "spank", "grab tits", "grab butt", "legs together"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed", "couch"]
    },
    {
        "name": "like lovers do",
        "flavor": "...to hold you like lovers do, and I do.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 4,
        "roughness": 3,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "kiss", "eye contact"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["bed", "couch"]
    },
    {
        "name": "pussy planking",
        "flavor": "Planks are hard enough on their own...",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 5,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    },
    {
        "name": "bottoming out",
        "flavor": "He's bottoming out inside your pussy... It's so deep.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 8,
        "roughness": 9,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 10,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "manhandled", "balls deep"],
        "skill": "passive sex",
        "skill level": 9,
        "locations": ["bed", "couch"]
    },
    {
        "name": "so deep",
        "flavor": "He's so deep inside.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 4,
        "roughness": 7,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "balls deep", "eye contact", "boobs jiggle", "legs together"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed", "couch"]
    },
    {
        "name": "splitting you open",
        "flavor": "He holds your legs up and split open... while he splits you open.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 7,
        "roughness": 6,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "balls deep", "eye contact", "boobs jiggle", "he spreads your legs"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["bed", "couch"]
    },
    {
        "name": "spread eagle",
        "flavor": "He spreads you open and plunders that pussy.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 5,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "legs in the air",  "boobs jiggle", "he spreads your legs"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    },
    {
        "name": "stretch you out",
        "flavor": "Your pussy wraps around his cock as it stretches you out.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "legs in the air",  "kiss"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    }
)
positions("lana", "passive", "service",
    {
        "name": "over the shoulder snacktime",
        "flavor": "Hop up on his shoulder, so he can reach his snack better.",
        "type": "passive",
        "subtype": "service",
        "position": "cunnilingus",
        "athletics": 6,
        "roughness": 3,
        "your pleasure": 6,
        "pleasure factor": "oral",
        "his pleasure": 0,
        "his satisfaction": 0,
        "rhythm": 500,
        "tags": ["black", "pussy licking"],
        "skill": "orgasm control",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "facefuck deepthroat",
        "flavor": "You try to keep up, but he takes control and forces your head down.",
        "type": "passive",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "sloppy", "close to crotch", "deepthroat", "facefuck", "helpless"],
        "skill": "gag reflex",
        "skill level": 7,
        "locations": ["floor"]
    },
    {
        "name": "pussy motorboating",
        "flavor": "He motorboats your pussy.",
        "type": "passive",
        "subtype": "service",
        "position": "cunnilingus",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "oral",
        "his pleasure": 0,
        "his satisfaction": 0,
        "rhythm": 500,
        "tags": ["black", "pussy licking", "sloppy"],
        "skill": "orgasm control",
        "skill level": 6,
        "locations": ["couch"]
    }
)