init_character_for_position("jade")

positions("jade", "active", "cowgirl",
    {
        "name": "at the rodeo",
        "flavor": "Ride 'em cowgirl.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "grab butt", "balls deep"],
        "skill": "active sex",
        "skill level": 6,
        "locations": ["couch","bed"]
    },
    {
        "name": "back it up",
        "flavor": "Go on, back it up... and down, on his dick.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "butt view", "grab waist", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["bed"]
    },
    {
        "name": "bouncing betties",
        "flavor": "You aren't Betty, but they're bouncing.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "grab waist", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["bed"]
    },
    {
        "name": "impale yourself on BBC",
        "flavor": "It's so big compared to your tiny hole, there really isn't a better way to describe it.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "butt view", "grab boobs", "butt jiggle"],
        "skill": "active sex",
        "skill level": 7,
        "locations": ["couch","bed"]
    },
    {
        "name": "keep your balance",
        "flavor": "He may be holding you up, but you have to balance yourself somehow.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 8,
        "roughness": 5,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "eye contact", "grab waist", "boobs jiggle", "balance with feet"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "pogo stick",
        "flavor": "Ride that dick like a pogo stick.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 9,
        "roughness": 10,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "butt view", "grab butt", "boobs jiggle", "spank"],
        "skill": "active sex",
        "skill level": 8,
        "locations": ["bed"]
    },
    {
        "name": "slide on down",
        "flavor": "He guides you as you slide down on that dick.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "butt view", "grab butt", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["bed"]
    }
)
positions("jade", "active", "doggy",
    {
        "name": "sliding back",
        "flavor": "You slide that tight butt back onto his cock.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 5,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "balls deep", "prone", "butt jiggle", "all fours", "look back"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["bed"]
    }
)
positions("jade", "active", "missionary",
    {
        "name": "rubbing and pounding",
        "flavor": "He slows down a little, giving you a chance to rub your clit.",
        "type": "active",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 4,
        "roughness": 6,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "balls deep", "touch yourself"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["bed"]
    }
)
positions("jade", "active", "service",
    {
        "name": "a tit jerk",
        "flavor": "You mean a tit job? No? A tit jerk? Huh. Well as long as you're having fun...",
        "type": "active",
        "subtype": "service",
        "position": "titfuck",
        "athletics": 3,
        "roughness": 2,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 6,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "titfuck", "jerking"],
        "skill": "titfuck",
        "skill level": 2,
        "locations": ["bed"]
      },
      {
        "name": "amateur blowjob",
        "flavor": "Are you sure you know what you're doing?",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 2,
        "roughness": 1,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 6,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "blowjob"],
        "skill": "blowjob",
        "skill level": 1,
        "locations": ["bed"]
      },
      {
        "name": "the preamble",
        "flavor": "You're just getting started...",
        "type": "active",
        "subtype": "service",
        "position": "handjob",
        "athletics": 3,
        "roughness": 3,
        "your pleasure": 6,
        "pleasure factor": "oral",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "jerking", "kiss", "fingering"],
        "skill": "handjob",
        "skill level": 4,
        "locations": ["bed"]
      },
      {
        "name": "tiny hands wrapped around a BBC",
        "flavor": "Either your hands are tiny... or his cock is huge...",
        "type": "active",
        "subtype": "service",
        "position": "handjob",
        "athletics": 3,
        "roughness": 2,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "jerking", "licking"],
        "skill": "handjob",
        "skill level": 4,
        "locations": ["couch"]
      },
      {
        "name": "two handed blowjob",
        "flavor": "It's so big, you need both hands... and your mouth.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 3,
        "roughness": 3,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "jerking", "licking","eye contact"],
        "skill": "blowjob",
        "skill level": 4,
        "locations": ["couch"]
      },
      {
        "name": "use both hands",
        "flavor": "This job definitely requires both hands. Warm it up for your pussy.",
        "type": "active",
        "subtype": "service",
        "position": "handjob",
        "athletics": 3,
        "roughness": 2,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "eye contact", "jerking"],
        "skill": "blowjob",
        "skill level": 4,
        "locations": ["bed"]
      },
      {
        "name": "worship BBC",
        "flavor": "BBC is your new God. Worship it.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 3,
        "roughness": 4,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "balls in face", "lick balls","sloppy"],
        "skill": "blowjob",
        "skill level": 5,
        "locations": ["bed","couch"]
      }
)
positions("jade", "passive", "cowgirl",
    {
        "name": "a firm grASSp",
        "flavor": "He takes a firm grASSp on you.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 2,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "butt view", "grab butt", "butt jiggle", "spank"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "deep thrusts",
        "flavor": "He holds you up and thrusts his chocolate fuckstick deep inside.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "big thrusts", "grab butt", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "dickhammering",
        "flavor": "It's like jackhammering, but... ya know, with his dick.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 7,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "butt view", "grab butt"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "held up and pounded",
        "flavor": "He lifts you and sets you down on his cock, then starts pounding.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 7,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "eyes roll", "legs in the air", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["couch"]
    },
    {
        "name": "hitting all the right spots",
        "flavor": "He positions himself, just right, to be able to hit each of your pleasure centers.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 6,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "butt view", "grab butt", "look back"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "hugged and hammered",
        "flavor": "He holds you close and slams that jackhammer in, over and over.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 2,
        "roughness": 4,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "romantic", "balls deep", "hug"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "legs together",
        "flavor": "He pulls you back into him, holding your legs up in the air, and keeps pumping.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 7,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "balls smacking", "legs in the air", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "legs up",
        "flavor": "He's so strong, he tosses your legs up like you're a feather.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eyes roll", "legs in the air", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "pounded from below",
        "flavor": "With ASSets in hand, he takes you to pound town.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "balls deep", "grab butt", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "properly pounded",
        "flavor": "He's giving you a proper pounding. You might be sore tomorrow...",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 8,
        "roughness": 10,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 10,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "butt view", "grab shoulders", "butt jiggle", "big thrusts"],
        "skill": "passive sex",
        "skill level": 9,
        "locations": ["bed"]
    },
    {
        "name": "reclined reverse cowgirl",
        "flavor": "You lean back into him, he doesn't slow down.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "big thrusts", "grab butt", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "reverse spread open",
        "flavor": "He spreads your legs open, holding them in the air.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 5,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "look back", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "til your eyes roll back",
        "flavor": ".",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "butt view", "grab butt", "boobs jiggle", "eyes roll"],
        "skill": "passive sex",
        "skill level": 8,
        "locations": ["couch"]
    }

)
positions("jade", "passive", "doggy",
    {
        "name": "can't stop won't stop",
        "flavor": "Even if he wanted to, he's not stopping.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 8,
        "roughness": 9,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "grab sheets", "balls deep", "all fours"],
        "skill": "passive sex",
        "skill level": 8,
        "locations": ["bed"]
    },
    {
        "name": "cross legged",
        "flavor": "One leg over the other, gives him the best angles.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab butt", "boobs jiggle", "eyes roll"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "face down ass up",
        "flavor": "That's the way we like to fuck.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 7,
        "roughness": 7,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "spank", "balls deep", "look back", "prone"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "feels so good",
        "flavor": "Why does it feel so damn good?",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 8,
        "roughness": 6,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab leg", "balls deep", "eye contact"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["bed"]
    },
    {
        "name": "just getting started",
        "flavor": "Better get comfortable, he's just getting started...",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 3,
        "roughness": 3,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "grab waist", "eyes roll", "look back"],
        "skill": "passive sex",
        "skill level": 2,
        "locations": ["couch"]
    },
    {
        "name": "lay there and take it",
        "flavor": "Go on, take a break. He isn't going to, but you can rest up.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 4,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "spank", "eyes roll", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "on all fours",
        "flavor": "Welcome to pleasuretown, population you.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 7,
        "roughness": 7,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "pull hair", "balls deep", "eyes roll", "boobs jiggle", "all fours"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["couch"]
    },
    {
        "name": "ruff doggy",
        "flavor": "He smacks that ass til it turns red.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 4,
        "roughness": 9,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 10,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "grab butt", "balls deep", "look back", "spank", "grab sheets"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "side saddle",
        "flavor": "Just like a proper lady riding a stallion.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 7,
        "roughness": 6,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab butt", "spank", "look back", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["couch"]
    },
    {
        "name": "sideways from behind",
        "flavor": "Laid on your side and then... well, laid.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "kiss", "balls deep", "look back"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "spread em open",
        "flavor": "Spread those cheeks open for daddy.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "big thrusts", "boobs jiggle", "eye contact"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    }
)
positions("jade", "passive", "missionary",
    {
        "name": "advanced missionary",
        "flavor": "He's really got the hang of it.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "eye contact", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 8,
        "locations": ["bed"]
    },
    {
        "name": "cock sleeve",
        "flavor": "Your tight pussy hugs his cock like a sleeve.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 5,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "boobs jiggle", "eyes roll"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "feel like makin love",
        "flavor": "Baby, when I think about you... I think about love.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 2,
        "roughness": 3,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "kiss", "romantic"],
        "skill": "passive sex",
        "skill level": 2,
        "locations": ["bed"]
    },
    {
        "name": "legs wrapped around",
        "flavor": "You instinctively wrap your legs around him.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "kiss"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["bed"]
    },
    {
        "name": "medium missionary",
        "flavor": "That's a bit better now, isn't it?",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 5,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "big thrusts"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "oiled up",
        "flavor": "A small pit stop for oil, then right back to it.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 5,
        "roughness": 6,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "eye contact", "boobs jiggle", "legs in the air"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "one leg up",
        "flavor": "He holds one leg up while he pounds you.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 4,
        "roughness": 6,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "grab boobs", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "sideways",
        "flavor": "From this angle, it's going all the way in... and it feels so good.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 7,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "boobs jiggle", "balls deep", "balls smacking"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "t-bone",
        "flavor": "You're both completely sideways. Whatever he's doing down there... it's working.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 8,
        "roughness": 9,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "eye contact", "boobs jiggle", "balls deep", "balls smacking"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["bed"]
    },
    {
        "name": "the long game",
        "flavor": "He's playing the long game... with his dick.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 2,
        "roughness": 3,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "eye contact", "easy", "big thrusts"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["bed"]
    },
    {
        "name": "the right angles",
        "flavor": "He tosses a leg up and goes to town.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 5,
        "roughness": 5,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "boobs jiggle", "big thrusts"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["couch"]
    },
    {
        "name": "titty twister",
        "flavor": "He doesn't just grab your boob, he twists your titty.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 3,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "grab boobs"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["couch"]
    },
    {
        "name": "watch him put it in",
        "flavor": "With your head propped up, you get to watch it go in... and out... and in...",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["couch"]
    }
)
positions("jade", "passive", "service",
    {
        "name": "a good lickin",
        "flavor": "He bends you over and gives you a good lickin.",
        "type": "passive",
        "subtype": "service",
        "position": "cunnilingus",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 8,
        "pleasure factor": "oral",
        "his pleasure": 0,
        "his satisfaction": 0,
        "rhythm": 500,
        "tags": ["black", "pussy licking"],
        "skill": "orgasm control",
        "skill level": 4,
        "locations": ["standing"]
    },
    {
        "name": "facehugger",
        "flavor": "Your face wants to hug his cock.",
        "type": "passive",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "sloppy", "close to crotch", "facefuck", "helpless"],
        "skill": "gag reflex",
        "skill level": 7,
        "locations": ["floor","couch","bed"]
    },
    {
        "name": "titfuck",
        "flavor": "It's not the best, but he tries to fuck your tit pussy.",
        "type": "passive",
        "subtype": "service",
        "position": "titfuck",
        "athletics": 5,
        "roughness": 4,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "titfuck", "close to crotch"],
        "skill": "titfuck",
        "skill level": 4,
        "locations": ["floor"]
      }
)
