init_character_for_position("rae")

positions("rae", "active", "cowgirl",
    {
        "name": "romantic riding",
        "flavor": "His hands on your hips, he guides you down onto his cock.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 2,
        "roughness": 4,
        "your pleasure": 6,
        "pleasure factor": "length",
        "his pleasure": 5,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "butt view", "romantic"],
        "skill": "active sex",
        "skill level": 2,
        "locations": ["bed", "couch"]
    },
    {
        "name": "pole rider",
        "flavor": "He holds you in place while he impales you.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 9,
        "your pleasure": 8,
        "pleasure factor": "length",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "manhandled", "balls smacking"],
        "skill": "active sex",
        "skill level": 7,
        "locations": ["bed", "couch"]
    },
    {
        "name": "cowgirl spanking",
        "flavor": "You timidly slap your own ass while you ride him.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "spank", "look back"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["bed", "couch"]
    },
    {
        "name": "bouncing on BBC",
        "flavor": "Bounce that cute lil' butt up and down on BBC.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 7,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab waist", "eye contact", "kiss"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["bed", "couch"]
    },
    {
        "name": "deep grind",
        "flavor": "You grind your hips into his as you lean in for a kiss.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 3,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab boobs", "kiss", "romantic"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    },
    {
        "name": "meet him halfway",
        "flavor": "Don't just lay there, bounce up and down a bit.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "butt jiggle", "spank", "grab waist"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["bed", "couch"]
    },
    {
        "name": "standing cowgirl",
        "flavor": "Wait, so it's standing... and it's cowgirl?",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 8,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 7,
        "locations": ["table"]
    }
)
positions("rae", "active", "doggy",
    {
        "name": "flamingo fuck",
        "flavor": "Balancing on one leg, he bends you over the couch.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 8,
        "roughness": 9,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "manhandled", "balls deep", "boobs jiggle","balls smacking","eye contact"],
        "skill": "active sex",
        "skill level": 7,
        "locations": ["couch"]
    }
)
positions("rae", "active", "missionary",
    {
        "name": "slow and sensual",
        "flavor": "Almost feels like prom night.",
        "type": "active",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 2,
        "roughness": 2,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 5,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "kiss", "balls deep", "romantic"],
        "skill": "active sex",
        "skill level": 2,
        "locations": ["bed", "couch"]
    },
    {
        "name": "choke fuck",
        "flavor": "Having trouble breathing are we?",
        "type": "active",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "choke", "manhandled", "boobs jiggle", "eye contact"],
        "skill": "active sex",
        "skill level": 6,
        "locations": ["bed", "couch"]
    },
    {
        "name": "passionate",
        "flavor": "He pulls you close, he's so deep.",
        "type": "active",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "kiss", "balls deep", "romantic", "eye contact"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["bed", "couch"]
    },
    {
        "name": "do all the work",
        "flavor": "Let him lie there while you do all the work.",
        "type": "active",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 8,
        "roughness": 4,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "standing", "eye contact", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["table"]
    }
)
positions("rae", "active", "service",
    {
      "name": "girl you nasty",
      "flavor": "Aww, that's nasty.",
      "type": "active",
      "subtype": "service",
      "position": "blowjob",
      "athletics": 4,
      "roughness": 3,
      "your pleasure": 0,
      "pleasure factor": "none",
      "his pleasure": 7,
      "his satisfaction": 7,
      "rhythm": 500,
      "tags": ["black", "close to crotch", "balls in face", "licking"],
      "skill": "handjob",
      "skill level": 5,
      "locations": ["bed"]
    },
    {
        "name": "69",
        "flavor": "Pleasure him while he pleasures you.",
        "type": "active",
        "subtype": "service",
        "position": "69",
        "athletics": 5,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "oral",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "blowjob"],
        "skill": "blowjob",
        "skill level": 3,
        "locations": ["bed"]
      },
      {
        "name": "worship BBC",
        "flavor": "BBC is your new God. Worship it.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 4,
        "roughness": 3,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "blowjob", "jerking"],
        "skill": "blowjob",
        "skill level": 4,
        "locations": ["floor"]
      }
)
positions("rae", "passive", "cowgirl",
    {
        "name": "hair hold",
        "flavor": "He grabs your hair, holding you in place while he pounds you.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "butt view", "grab hair", "manhandled"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed", "couch"]
    },
    {
        "name": "walking on sunshine",
        "flavor": "... and it makes you feel good.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "grab waist", "balance with feet"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["bed", "couch"]
    },
    {
        "name": "split you open",
        "flavor": "Show off your flexiblity by doing splits on that cock.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 10,
        "roughness": 8,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "butt view", "grab waist"],
        "skill": "passive sex",
        "skill level": 8,
        "locations": ["bed"]
    }
)
positions("rae", "passive", "doggy",
    {
        "name": "fucktoy",
        "flavor": "Your name is Fucktoy. You belong to him.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 10,
        "roughness": 10,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 10,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "manhandled", "grab hair", "grab waist", "balls smacking"],
        "skill": "passive sex",
        "skill level": 10,
        "locations": ["bed", "couch"]
    },
    {
        "name": "kitchen sink",
        "flavor": "He's throwing everything at you except the kitchen sink.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["standing"]
    },
    {
        "name": "podracing doggy",
        "flavor": "Now this is podracing?",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 7,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab waist", "balls deep"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "sidefuck",
        "flavor": "Is it supposed to feel this good?",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 4,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab waist", "balls deep", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["couch"]
    },
    {
        "name": "deep and slow",
        "flavor": "He holds you down and fucks you... deeply and slowly.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 4,
        "roughness": 5,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab boobs", "balls deep", "look back"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    },
    {
        "name": "pounded from behind",
        "flavor": "He tosses you around like you're nothing. Nothing but a warm hole for him to pound.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 5,
        "roughness": 8,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab waist", "balls deep", "look back", "eyes roll"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "the build up",
        "flavor": "He starts off slow, then picks up the pace.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 4,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab waist", "boobs jiggle", "hair swish"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["standing"]
    }
)
positions("rae", "passive", "missionary",
    {
        "name": "legs up squat",
        "flavor": "He holds you down while he impales you.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 5,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "balls deep", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed", "couch"]
    },
    {
        "name": "standing fuck",
        "flavor": "He's holding you up by your ass, as he slams into your pussy.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 9,
        "roughness": 9,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "butt view", "legs in the air", "balls deep", "manhandled", "grab butt", "standing fuck"],
        "skill": "passive sex",
        "skill level": 8,
        "locations": ["standing"]
    },
    {
        "name": "choke legs up",
        "flavor": "His hand around your neck, he pounds you mercilessly.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 7,
        "roughness": 9,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "balls deep", "manhandled", "boobs jiggle", "standing fuck"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["standing"]
    },
    {
        "name": "pinned and pounded",
        "flavor": "He has you pinned while he dicks you down.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 4,
        "roughness": 6,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "balls deep", "manhandled", "boobs jiggle", "mating press"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["standing"]
    },
    {
        "name": "deeper",
        "flavor": "So deep... he's so deep.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "balls deep", "kiss", "boobs jiggle", "mating press"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    },
    {
        "name": "chair fuck",
        "flavor": "Any surface will do.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "balls deep", "grab boobs", "grab head"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["chair"]
    },
    {
        "name": "criss cross",
        "flavor": "Hey, ho.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 9,
        "roughness": 6,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "balls deep"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    },
    {
        "name": "intimate missionary",
        "flavor": "Your two bodies become one... and it feels so good.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 5,
        "roughness": 7,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "legs in the air", "balls deep", "mating press", "kiss"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed"]
    }
)
positions("rae", "passive", "service", 
    {
        "name": "facefuck",
        "flavor": "Your throat is his fleshlight.",
        "type": "passive",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 8,
        "roughness": 10,
        "your pleasure": 0,
        "pleasure factor": "oral",
        "his pleasure": 7,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "sloppy", "close to crotch", "deepthroat", "facefuck", "submissive", "helpless", "mandhandled"],
        "skill": "gag reflex",
        "skill level": 7,
        "locations": ["bed", "couch"]
    },
    {
        "name": "standing oral",
        "flavor": "He lifted you up like you were a feather.",
        "type": "passive",
        "subtype": "service",
        "position": "cunnilingus",
        "athletics": 9,
        "roughness": 4,
        "your pleasure": 8,
        "pleasure factor": "oral",
        "his pleasure": 0,
        "his satisfaction": 0,
        "rhythm": 500,
        "tags": ["black", "submissive", "helpless", "pussy licking", "ass up"],
        "skill": "orgasm control",
        "skill level": 5,
        "locations": ["standing"]
    },
    {
        "name": "spiderman",
        "flavor": "You don't get it. He told you it was from an old movie and it'd be hot.",
        "type": "passive",
        "subtype": "service",
        "position": "fingering",
        "athletics": 4,
        "roughness": 0,
        "your pleasure": 5,
        "pleasure factor": "oral",
        "his pleasure": 0,
        "his satisfaction": 0,
        "rhythm": 500,
        "tags": ["black", "fingering", "kiss"],
        "skill": "orgasm control",
        "skill level": 3,
        "locations": ["bed"]
    }
)
