outfits("alina", "gym",
  {
    "name": "blacked original",
    "flavor": "Featuring the original BLACKED logo band, this is a sporty look that feels sexy every day.",
    "description": "blacked underwear",
    "price": 200, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["workout","chad magnet","blacked"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Sports Bra",
    "bottom": "BLACKED Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked white",
    "flavor": "The *White* Set. Light, bright, and unmistakably BLACKED.",
    "description": "blacked underwear",
    "price": 250, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "slutty",
    "tags": ["great workout","fuckboy magnet","blacked"],
    "colors": ["white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED White Sports Bra",
    "bottom": "BLACKED White Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked red",
    "flavor": "10th anniversary edition! Celebrate in style with this bold BLACKED look.",
    "description": "blacked underwear",
    "price": 300, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["great workout","rich magnet","blacked"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Red Sports Bra",
    "bottom": "BLACKED Red Thong Panties",
    "shoes": "none" 
  }
)

outfits("alina", "beach",
  {
    "name": "blacked onepiece",
    "flavor": "Bold, daring, and unmistakably BLACKED – make waves everywhere you go!",
    "description": "Blacked Swimsuit",
    "price": 180, 
    "type": "one-piece swimsuit",
    "sluttiness": 6,
    "comfort": 7,
    "durability": 8,
    "style": "sexy",
    "tags": ["waterproof","jock magnet","blacked"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 4,
    "locations": ["beach","fetish"],
    "onepiece": "BLACKED Swimsuit",
    "shoes": "none" 
  }
)

outfits("alina", "casual",
  {
    "name": "blacked jersey",
    "flavor": "The Iconic 23. Inspired by the GOAT, made for legends like you.",
    "description": "Blacked Jersey",
    "price": 360, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked"],
    "colors": ["red","black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "onepiece": "BLACKED Red Jersey",
    "shoes": "none" 
  },
  {
    "name": "blacked and white",
    "flavor": "BLACKED and White. The perfect combination.",
    "description": "Blacked Sporty Outfit",
    "price": 190, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","chad magnet","blacked"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "White cropped BLACKED bralette",
    "bottom": "BLACKED high-waisted shorts",
    "shoes": "sneakers" 
  }
)

outfits("ella", "gym",
  {
    "name": "blacked original",
    "flavor": "Featuring the original BLACKED logo band, this is a sporty look that feels sexy every day.",
    "description": "blacked underwear",
    "price": 200, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["workout","chad magnet","blacked"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Sports Bra",
    "bottom": "BLACKED Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked white",
    "flavor": "The *White* Set. Light, bright, and unmistakably BLACKED.",
    "description": "blacked underwear",
    "price": 250, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "slutty",
    "tags": ["great workout","fuckboy magnet","blacked"],
    "colors": ["white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED White Sports Bra",
    "bottom": "BLACKED White Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked red",
    "flavor": "10th anniversary edition! Celebrate in style with this bold BLACKED look.",
    "description": "blacked underwear",
    "price": 300, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["great workout","rich magnet","blacked"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Red Sports Bra",
    "bottom": "BLACKED Red Thong Panties",
    "shoes": "none" 
  }
)

outfits("ella", "beach",
  {
    "name": "blacked onepiece",
    "flavor": "Bold, daring, and unmistakably BLACKED – make waves everywhere you go!",
    "description": "Blacked Swimsuit",
    "price": 180, 
    "type": "one-piece swimsuit",
    "sluttiness": 6,
    "comfort": 7,
    "durability": 8,
    "style": "sexy",
    "tags": ["waterproof","jock magnet","blacked"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 4,
    "locations": ["beach","fetish"],
    "onepiece": "BLACKED Swimsuit",
    "shoes": "none" 
  }
)

outfits("ella", "casual",
  {
    "name": "blacked jersey",
    "flavor": "The Iconic 23. Inspired by the GOAT, made for legends like you.",
    "description": "Blacked Jersey",
    "price": 360, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked"],
    "colors": ["red","black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "onepiece": "BLACKED Red Jersey",
    "shoes": "sneakers" 
  }
)

outfits("ella", "stylin",
  {
    "name": "blacked bling",
    "flavor": "AVN bling edition! Shine like a star in this exclusive BLACKED look.",
    "description": "blacked blingwear",
    "price": 499, 
    "type": "stylin",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "slutty",
    "tags": ["rich magnet","blacked"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["lingerie","fetish","stylin"],
    "top": "BLACKED Rhinestone-Covered Sports Bra and Gloves",
    "bottom": "BLACKED BLINGED Rhinestone-Covered Thong Panties",
    "shoes": "heeled boots" 
  }
)

outfits("jade", "gym",
  {
    "name": "blacked original",
    "flavor": "Featuring the original BLACKED logo band, this is a sporty look that feels sexy every day.",
    "description": "blacked underwear",
    "price": 200, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["workout","chad magnet","blacked"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Sports Bra",
    "bottom": "BLACKED Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked white",
    "flavor": "The *White* Set. Light, bright, and unmistakably BLACKED.",
    "description": "blacked underwear",
    "price": 250, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "slutty",
    "tags": ["great workout","fuckboy magnet","blacked"],
    "colors": ["white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED White Sports Bra",
    "bottom": "BLACKED White Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked red",
    "flavor": "10th anniversary edition! Celebrate in style with this bold BLACKED look.",
    "description": "blacked underwear",
    "price": 300, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["great workout","rich magnet","blacked"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Red Sports Bra",
    "bottom": "BLACKED Red Thong Panties",
    "shoes": "none" 
  }
)

outfits("jade", "beach",
  {
    "name": "blacked onepiece",
    "flavor": "Bold, daring, and unmistakably BLACKED – make waves everywhere you go!",
    "description": "Blacked Swimsuit",
    "price": 180, 
    "type": "one-piece swimsuit",
    "sluttiness": 6,
    "comfort": 7,
    "durability": 8,
    "style": "sexy",
    "tags": ["waterproof","jock magnet","blacked"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 4,
    "locations": ["beach","fetish"],
    "onepiece": "BLACKED Swimsuit",
    "shoes": "none" 
  }
)

outfits("jade", "casual",
  {
    "name": "blacked jersey",
    "flavor": "The Iconic 23. Inspired by the GOAT, made for legends like you.",
    "description": "Blacked Jersey",
    "price": 360, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked"],
    "colors": ["red","black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "onepiece": "BLACKED Red Jersey",
    "shoes": "none" 
  }
)

outfits("jade", "stylin",
  {
    "name": "blacked dress",
    "flavor": "Make a statement in this fashionable form-fitting BLACKED mini dress.",
    "description": "Blacked Mini Dress",
    "price": 380, 
    "type": "dress",
    "sluttiness": 6,
    "comfort": 8,
    "durability": 8,
    "style": "sexy",
    "tags": ["rich magnet","blacked"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 5,
    "locations": ["stylin","fetish"],
    "onepiece": "BLACKED Dress",
    "shoes": "high heels"
  }
)

outfits("jia", "beach",
  {
    "name": "blacked onepiece",
    "flavor": "Bold, daring, and unmistakably BLACKED – make waves everywhere you go!",
    "description": "Blacked Swimsuit",
    "price": 180, 
    "type": "one-piece swimsuit",
    "sluttiness": 6,
    "comfort": 7,
    "durability": 8,
    "style": "sexy",
    "tags": ["waterproof","fuckboy magnet","blacked"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 4,
    "locations": ["beach","fetish"],
    "onepiece": "BLACKED Swimsuit",
    "shoes": "none" 
  }
)

outfits("jia", "gym",
  {
    "name": "blacked original",
    "flavor": "Featuring the original BLACKED logo band, this is a sporty look that feels sexy every day.",
    "description": "blacked underwear",
    "price": 200, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["workout","chad magnet","blacked"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Sports Bra",
    "bottom": "BLACKED Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked white",
    "flavor": "The *White* Set. Light, bright, and unmistakably BLACKED.",
    "description": "blacked underwear",
    "price": 250, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "slutty",
    "tags": ["great workout","fuckboy magnet","blacked"],
    "colors": ["white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED White Sports Bra",
    "bottom": "BLACKED White Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked yoga",
    "flavor": "Move, stretch, and slay – the Rosé Luxe set is BLACKED sophistication in motion.",
    "description": "blacked yoga outfit",
    "price": 280, 
    "type": "activewear",
    "sluttiness": 6,
    "comfort": 10,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","fuckboy magnet","blacked"],
    "colors": ["pink","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED White Sports Bra with Pink Jacket",
    "bottom": "BLACKED Pink High-Waisted Yoga Pants",
    "shoes": "sneakers" 
  },
  {
    "name": "blacked red",
    "flavor": "10th anniversary edition! Celebrate in style with this bold BLACKED look.",
    "description": "blacked underwear",
    "price": 300, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["great workout","rich magnet","blacked"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Red Sports Bra",
    "bottom": "BLACKED Red Thong Panties",
    "shoes": "none" 
  }
)

outfits("jia", "casual",
  {
    "name": "blacked jersey",
    "flavor": "The Iconic 23. Inspired by the GOAT, made for legends like you.",
    "description": "Blacked Jersey",
    "price": 360, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked"],
    "colors": ["red","black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "onepiece": "BLACKED Red Jersey",
    "shoes": "none" 
  }
)

outfits("lana", "gym",
  {
    "name": "blacked original",
    "flavor": "Featuring the original BLACKED logo band, this is a sporty look that feels sexy every day.",
    "description": "blacked underwear",
    "price": 200, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["workout","chad magnet","blacked"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Sports Bra",
    "bottom": "BLACKED Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked white",
    "flavor": "The *White* Set. Light, bright, and unmistakably BLACKED.",
    "description": "blacked underwear",
    "price": 250, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "slutty",
    "tags": ["great workout","fuckboy magnet","blacked"],
    "colors": ["white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED White Sports Bra",
    "bottom": "BLACKED White Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked red",
    "flavor": "10th anniversary edition! Celebrate in style with this bold BLACKED look.",
    "description": "blacked underwear",
    "price": 300, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["great workout","rich magnet","blacked"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Red Sports Bra",
    "bottom": "BLACKED Red Thong Panties",
    "shoes": "none" 
  }
)

outfits("lana", "casual",
  {
    "name": "blacked onepiece",
    "flavor": "Bold, daring, and unmistakably BLACKED – make waves everywhere you go!",
    "description": "blacked leotard",
    "price": 230, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 7,
    "durability": 8,
    "style": "slutty",
    "tags": ["waterproof","fuckboy magnet","blacked"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 4,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "onepiece": "BLACKED Leotard",
    "shoes": "none" 
  },
  {
    "name": "blacked jersey",
    "flavor": "The Iconic 23. Inspired by the GOAT, made for legends like you.",
    "description": "Blacked Jersey",
    "price": 360, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked"],
    "colors": ["red","black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "onepiece": "BLACKED Red Jersey",
    "shoes": "sneakers" 
  },
  {
    "name": "blacked rebel",
    "flavor": "Rebel in style with this BLACKED look.",
    "description": "blacked jacket and bodysuit",
    "price": 420, 
    "type": "casual",
    "sluttiness": 10,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["chad magnet","blacked"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["cleavage","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["fetish","casual","stylin"],
    "top": "BLACKED cropped faux-leather jacket",
    "bottom": "BLACKED red thong bodysuit with fishnets",
    "shoes": "heeled boots" 
  }
)

outfits("liya", "gym",
  {
    "name": "blacked original",
    "flavor": "Featuring the original BLACKED logo band, this is a sporty look that feels sexy every day.",
    "description": "blacked underwear",
    "price": 200, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["workout","chad magnet","blacked"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Sports Bra",
    "bottom": "BLACKED Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked white",
    "flavor": "The *White* Set. Light, bright, and unmistakably BLACKED.",
    "description": "blacked underwear",
    "price": 250, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "slutty",
    "tags": ["great workout","fuckboy magnet","blacked"],
    "colors": ["white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED White Sports Bra",
    "bottom": "BLACKED White Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked red",
    "flavor": "10th anniversary edition! Celebrate in style with this bold BLACKED look.",
    "description": "blacked underwear",
    "price": 300, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["great workout","rich magnet","blacked"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Red Sports Bra",
    "bottom": "BLACKED Red Thong Panties",
    "shoes": "none" 
  }
)

outfits("liya", "casual",
  {
    "name": "blacked onepiece",
    "flavor": "Bold, daring, and unmistakably BLACKED – make waves everywhere you go!",
    "description": "blacked leotard",
    "price": 230, 
    "type": "casual",
    "sluttiness": 10,
    "comfort": 7,
    "durability": 8,
    "style": "slutty",
    "tags": ["fuckboy magnet","blacked","stockings","long changing"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 4,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Leotard",
    "bottom": "Fishnet Stockings",
    "shoes": "thigh high heeled boots"
  },
  {
    "name": "blacked jersey",
    "flavor": "The Iconic 23. Inspired by the GOAT, made for legends like you.",
    "description": "Blacked Jersey",
    "price": 360, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked"],
    "colors": ["red","black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Red Jersey",
    "bottom": "Fishnet Stockings",
    "shoes": "heeled sneakers" 
  },
  {
    "name": "blacked and white",
    "flavor": "BLACKED and White. The perfect combination.",
    "description": "Blacked Sporty Outfit",
    "price": 190, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","chad magnet","blacked"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "White cropped BLACKED bralette",
    "bottom": "BLACKED Thong Panties",
    "shoes": "sneakers" 
  }
)

outfits("mia", "gym",
  {
    "name": "blacked original",
    "flavor": "Featuring the original BLACKED logo band, this is a sporty look that feels sexy every day.",
    "description": "blacked underwear",
    "price": 200, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["workout","chad magnet","blacked"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Sports Bra",
    "bottom": "BLACKED Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked white",
    "flavor": "The *White* Set. Light, bright, and unmistakably BLACKED.",
    "description": "blacked underwear",
    "price": 250, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "slutty",
    "tags": ["great workout","fuckboy magnet","blacked"],
    "colors": ["white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED White Sports Bra",
    "bottom": "BLACKED White Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked red",
    "flavor": "10th anniversary edition! Celebrate in style with this bold BLACKED look.",
    "description": "blacked underwear",
    "price": 300, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["great workout","rich magnet","blacked"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Red Sports Bra",
    "bottom": "BLACKED Red Thong Panties",
    "shoes": "none" 
  }
)

outfits("mia", "beach",
  {
    "name": "blacked onepiece",
    "flavor": "Bold, daring, and unmistakably BLACKED – make waves everywhere you go!",
    "description": "Blacked Swimsuit",
    "price": 180, 
    "type": "one-piece swimsuit",
    "sluttiness": 6,
    "comfort": 7,
    "durability": 8,
    "style": "sexy",
    "tags": ["waterproof","jock magnet","blacked"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 4,
    "locations": ["beach","fetish"],
    "onepiece": "BLACKED Swimsuit",
    "shoes": "none" 
  }
)

outfits("mia", "casual",
  {
    "name": "blacked jersey",
    "flavor": "The Iconic 23. Inspired by the GOAT, made for legends like you.",
    "description": "Blacked Jersey",
    "price": 360, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked"],
    "colors": ["red","black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","lots of cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "onepiece": "BLACKED Red Jersey",
    "shoes": "none" 
  },
  {
    "name": "blacked rebel",
    "flavor": "Rebel in style with this BLACKED look.",
    "description": "blacked jacket and bodysuit",
    "price": 420, 
    "type": "casual",
    "sluttiness": 10,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["chad magnet","blacked"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["cleavage","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["fetish","casual","stylin"],
    "top": "BLACKED cropped faux-leather jacket",
    "bottom": "BLACKED red thong bodysuit with fishnets",
    "shoes": "heeled boots" 
  }
)

outfits("rae", "gym",
  {
    "name": "blacked original",
    "flavor": "Featuring the original BLACKED logo band, this is a sporty look that feels sexy every day.",
    "description": "blacked underwear",
    "price": 200, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["workout","chad magnet","blacked"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Sports Bra",
    "bottom": "BLACKED Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked white",
    "flavor": "The *White* Set. Light, bright, and unmistakably BLACKED.",
    "description": "blacked underwear",
    "price": 250, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "slutty",
    "tags": ["great workout","fuckboy magnet","blacked"],
    "colors": ["white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED White Sports Bra",
    "bottom": "BLACKED White Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked red",
    "flavor": "10th anniversary edition! Celebrate in style with this bold BLACKED look.",
    "description": "blacked underwear",
    "price": 300, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["great workout","rich magnet","blacked"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Red Sports Bra",
    "bottom": "BLACKED Red Thong Panties",
    "shoes": "none" 
  }
)

outfits("rae", "casual",
  {
    "name": "blacked onepiece",
    "flavor": "Bold, daring, and unmistakably BLACKED – make waves everywhere you go!",
    "description": "blacked leotard",
    "price": 260, 
    "type": "casual",
    "sluttiness": 10,
    "comfort": 7,
    "durability": 8,
    "style": "slutty",
    "tags": ["fuckboy magnet","blacked","stockings","long changing"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 4,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Leotard",
    "bottom": "Fishnet Stockings",
    "shoes": "sneakers"
  },
  {
    "name": "blacked jersey",
    "flavor": "The Iconic 23. Inspired by the GOAT, made for legends like you.",
    "description": "Blacked Jersey",
    "price": 360, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked"],
    "colors": ["red","black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "onepiece": "BLACKED Red Jersey",
    "shoes": "none" 
  },
  {
    "name": "blacked cutoff",
    "flavor": "Was it already cut like that? or...",
    "description": "blacked cutoff",
    "price": 230, 
    "type": "casual",
    "sluttiness": 10,
    "comfort": 6,
    "durability": 8,
    "style": "slutty",
    "tags": ["fuckboy magnet","blacked"],
    "colors": ["gray","black"],
    "emphasizes": ["cleavage","boobs"],
    "reveals": ["legs","underboob"],
    "panties under": false,
    "bra under": false,
    "breast support": 2,
    "locations": ["fetish","casual","loungewear"],
    "top": "BLACKED cutoff",
    "bottom": "black panties",
    "shoes": "none" 
  }
)

outfits("scarlit", "gym",
  {
    "name": "blacked original",
    "flavor": "Featuring the original BLACKED logo band, this is a sporty look that feels sexy every day.",
    "description": "blacked underwear",
    "price": 200, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["workout","chad magnet","blacked"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Sports Bra",
    "bottom": "BLACKED Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked white",
    "flavor": "The *White* Set. Light, bright, and unmistakably BLACKED.",
    "description": "blacked underwear",
    "price": 250, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "slutty",
    "tags": ["great workout","fuckboy magnet","blacked"],
    "colors": ["white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED White Sports Bra",
    "bottom": "BLACKED White Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked red",
    "flavor": "10th anniversary edition! Celebrate in style with this bold BLACKED look.",
    "description": "blacked underwear",
    "price": 300, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["great workout","rich magnet","blacked"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "top": "BLACKED Red Sports Bra",
    "bottom": "BLACKED Red Thong Panties",
    "shoes": "none" 
  },
  {
    "name": "blacked yoga",
    "flavor": "Sporty meets stylish. BLACKED brings elegance to every workout.",
    "description": "blacked yoga outfit",
    "price": 280, 
    "type": "activewear",
    "sluttiness": 6,
    "comfort": 6,
    "durability": 10,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked"],
    "colors": ["black","pink"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","fetish","casual","loungewear"],
    "top": "BLACKED Pink Sports Bra",
    "bottom": "BLACKED Pink Leggings",
    "shoes": "sneakers" 
  }
)

outfits("scarlit", "casual",
  {
    "name": "blacked onepiece",
    "flavor": "Bold, daring, and unmistakably BLACKED – make waves everywhere you go!",
    "description": "blacked leotard",
    "price": 230, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 7,
    "durability": 8,
    "style": "slutty",
    "tags": ["waterproof","fuckboy magnet","blacked"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 4,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "onepiece": "BLACKED Leotard",
    "shoes": "none" 
  },
  {
    "name": "blacked jersey",
    "flavor": "The Iconic 23. Inspired by the GOAT, made for legends like you.",
    "description": "Blacked Jersey",
    "price": 360, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked"],
    "colors": ["red","black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","loungewear"],
    "onepiece": "BLACKED Red Jersey",
    "shoes": "none" 
  }
)
