outfits("alina", "gym",
  {
    "name": "blacked original",
    "flavor": "Featuring the original BLACKED logo band, this is a sporty look that feels sexy every day.",
    "description": "BLACKED underwear",
    "price": 200, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["workout","chad magnet","blacked","black magnet"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED sports bra",
    "bottom": "BLACKED thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked white",
    "flavor": "The *White* Set. Light, bright, and unmistakably BLACKED.",
    "description": "BLACKED underwear",
    "price": 250, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "slutty",
    "tags": ["great workout","fuckboy magnet","blacked","black magnet"],
    "colors": ["white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED white sports bra",
    "bottom": "BLACKED white thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked red",
    "flavor": "10th anniversary edition! Celebrate in style with this bold BLACKED look.",
    "description": "BLACKED underwear",
    "price": 300, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["great workout","rich magnet","blacked","black magnet"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED red sports bra",
    "bottom": "BLACKED red thong panties",
    "shoes": "none" 
  }
)

outfits("alina", "beach",
  {
    "name": "blacked onepiece",
    "flavor": "Bold, daring, and unmistakably BLACKED – make waves everywhere you go!",
    "description": "BLACKED Swimsuit",
    "price": 180, 
    "type": "one-piece swimsuit",
    "sluttiness": 6,
    "comfort": 7,
    "durability": 8,
    "style": "sexy",
    "tags": ["waterproof","jock magnet","blacked","black magnet"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 4,
    "locations": ["beach","fetish"],
    "onepiece": "BLACKED swimsuit",
    "shoes": "none" 
  }
)

outfits("alina", "casual",
  {
    "name": "blacked jersey",
    "flavor": "The Iconic 23. Inspired by the GOAT, made for legends like you.",
    "description": "BLACKED Jersey",
    "price": 360, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked","black magnet"],
    "colors": ["red","black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "onepiece": "BLACKED red jersey",
    "shoes": "none" 
  },
  {
    "name": "blacked and white",
    "flavor": "BLACKED and White. The perfect combination.",
    "description": "BLACKED Sporty Outfit",
    "price": 190, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","chad magnet","blacked","black magnet"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "white cropped BLACKED bralette",
    "bottom": "high-waisted BLACKED shorts",
    "shoes": "sneakers" 
  }
)

outfits("ella", "gym",
  {
    "name": "blacked original",
    "flavor": "Featuring the original BLACKED logo band, this is a sporty look that feels sexy every day.",
    "description": "BLACKED underwear",
    "price": 200, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["workout","chad magnet","blacked","black magnet"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED sports bra",
    "bottom": "BLACKED thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked white",
    "flavor": "The *White* Set. Light, bright, and unmistakably BLACKED.",
    "description": "BLACKED underwear",
    "price": 250, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "slutty",
    "tags": ["great workout","fuckboy magnet","blacked","black magnet"],
    "colors": ["white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED white sports bra",
    "bottom": "BLACKED white thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked red",
    "flavor": "10th anniversary edition! Celebrate in style with this bold BLACKED look.",
    "description": "BLACKED underwear",
    "price": 300, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["great workout","rich magnet","blacked","black magnet"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED red sports bra",
    "bottom": "BLACKED red thong panties",
    "shoes": "none" 
  }
)

outfits("ella", "beach",
  {
    "name": "blacked onepiece",
    "flavor": "Bold, daring, and unmistakably BLACKED – make waves everywhere you go!",
    "description": "BLACKED Swimsuit",
    "price": 180, 
    "type": "one-piece swimsuit",
    "sluttiness": 6,
    "comfort": 7,
    "durability": 8,
    "style": "sexy",
    "tags": ["waterproof","jock magnet","blacked","black magnet"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 4,
    "locations": ["beach","fetish"],
    "onepiece": "BLACKED swimsuit",
    "shoes": "none" 
  }
)

outfits("ella", "casual",
  {
    "name": "blacked jersey",
    "flavor": "The Iconic 23. Inspired by the GOAT, made for legends like you.",
    "description": "BLACKED Jersey",
    "price": 360, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked","black magnet"],
    "colors": ["red","black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "onepiece": "BLACKED red jersey",
    "shoes": "sneakers" 
  }
)

outfits("ella", "stylin",
  {
    "name": "blacked bling",
    "flavor": "AVN bling edition! Shine like a star in this exclusive BLACKED look.",
    "description": "BLACKED blingwear",
    "price": 499, 
    "type": "stylin",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "slutty",
    "tags": ["rich magnet","blacked","black magnet"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["lingerie","fetish","stylin"],
    "top": "BLACKED rhinestone-covered sports bra and gloves",
    "bottom": "BLACKED BLINGED rhinestone-covered thong panties",
    "shoes": "heeled boots" 
  }
)

outfits("jade", "gym",
  {
    "name": "blacked original",
    "flavor": "Featuring the original BLACKED logo band, this is a sporty look that feels sexy every day.",
    "description": "BLACKED underwear",
    "price": 200, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["workout","chad magnet","blacked","black magnet"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED sports bra",
    "bottom": "BLACKED thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked white",
    "flavor": "The *White* Set. Light, bright, and unmistakably BLACKED.",
    "description": "BLACKED underwear",
    "price": 250, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "slutty",
    "tags": ["great workout","fuckboy magnet","blacked","black magnet"],
    "colors": ["white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED white sports bra",
    "bottom": "BLACKED white thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked red",
    "flavor": "10th anniversary edition! Celebrate in style with this bold BLACKED look.",
    "description": "BLACKED underwear",
    "price": 300, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["great workout","rich magnet","blacked","black magnet"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED red sports bra",
    "bottom": "BLACKED red thong panties",
    "shoes": "none" 
  }
)

outfits("jade", "beach",
  {
    "name": "blacked onepiece",
    "flavor": "Bold, daring, and unmistakably BLACKED – make waves everywhere you go!",
    "description": "BLACKED Swimsuit",
    "price": 180, 
    "type": "one-piece swimsuit",
    "sluttiness": 6,
    "comfort": 7,
    "durability": 8,
    "style": "sexy",
    "tags": ["waterproof","jock magnet","blacked","black magnet"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 4,
    "locations": ["beach","fetish"],
    "onepiece": "BLACKED swimsuit",
    "shoes": "none" 
  }
)

outfits("jade", "casual",
  {
    "name": "blacked jersey",
    "flavor": "The Iconic 23. Inspired by the GOAT, made for legends like you.",
    "description": "BLACKED Jersey",
    "price": 360, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked","black magnet"],
    "colors": ["red","black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "onepiece": "BLACKED red jersey",
    "shoes": "none" 
  }
)

outfits("jade", "stylin",
  {
    "name": "blacked dress",
    "flavor": "Make a statement in this fashionable form-fitting BLACKED mini dress.",
    "description": "BLACKED Mini Dress",
    "price": 380, 
    "type": "dress",
    "sluttiness": 6,
    "comfort": 8,
    "durability": 8,
    "style": "sexy",
    "tags": ["rich magnet","blacked","black magnet"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 5,
    "locations": ["stylin","fetish"],
    "onepiece": "BLACKED dress",
    "shoes": "high heels"
  }
)

outfits("jia", "beach",
  {
    "name": "blacked onepiece",
    "flavor": "Bold, daring, and unmistakably BLACKED – make waves everywhere you go!",
    "description": "BLACKED Swimsuit",
    "price": 180, 
    "type": "one-piece swimsuit",
    "sluttiness": 6,
    "comfort": 7,
    "durability": 8,
    "style": "sexy",
    "tags": ["waterproof","fuckboy magnet","blacked","black magnet"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 4,
    "locations": ["beach","fetish"],
    "onepiece": "BLACKED swimsuit",
    "shoes": "none" 
  }
)

outfits("jia", "gym",
  {
    "name": "blacked original",
    "flavor": "Featuring the original BLACKED logo band, this is a sporty look that feels sexy every day.",
    "description": "BLACKED underwear",
    "price": 200, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["workout","chad magnet","blacked","black magnet"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED sports bra",
    "bottom": "BLACKED thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked white",
    "flavor": "The *White* Set. Light, bright, and unmistakably BLACKED.",
    "description": "BLACKED underwear",
    "price": 250, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "slutty",
    "tags": ["great workout","fuckboy magnet","blacked","black magnet"],
    "colors": ["white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED white sports bra",
    "bottom": "BLACKED white thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked yoga",
    "flavor": "Move, stretch, and slay – the Rosé Luxe set is BLACKED sophistication in motion.",
    "description": "BLACKED yoga outfit",
    "price": 280, 
    "type": "activewear",
    "sluttiness": 6,
    "comfort": 10,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","fuckboy magnet","blacked","black magnet"],
    "colors": ["pink","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED white sports bra with pink jacket",
    "bottom": "BLACKED pink high-waisted yoga Pants",
    "shoes": "sneakers" 
  },
  {
    "name": "blacked red",
    "flavor": "10th anniversary edition! Celebrate in style with this bold BLACKED look.",
    "description": "BLACKED underwear",
    "price": 300, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["great workout","rich magnet","blacked","black magnet"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED red sports bra",
    "bottom": "BLACKED red thong panties",
    "shoes": "none" 
  }
)

outfits("jia", "casual",
  {
    "name": "blacked jersey",
    "flavor": "The Iconic 23. Inspired by the GOAT, made for legends like you.",
    "description": "BLACKED Jersey",
    "price": 360, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked","black magnet"],
    "colors": ["red","black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "onepiece": "BLACKED red jersey",
    "shoes": "none" 
  }
)

outfits("lana", "gym",
  {
    "name": "blacked original",
    "flavor": "Featuring the original BLACKED logo band, this is a sporty look that feels sexy every day.",
    "description": "BLACKED underwear",
    "price": 200, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["workout","chad magnet","blacked","black magnet"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED sports bra",
    "bottom": "BLACKED thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked white",
    "flavor": "The *White* Set. Light, bright, and unmistakably BLACKED.",
    "description": "BLACKED underwear",
    "price": 250, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "slutty",
    "tags": ["great workout","fuckboy magnet","blacked","black magnet"],
    "colors": ["white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED white sports bra",
    "bottom": "BLACKED white thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked red",
    "flavor": "10th anniversary edition! Celebrate in style with this bold BLACKED look.",
    "description": "BLACKED underwear",
    "price": 300, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["great workout","rich magnet","blacked","black magnet"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED red sports bra",
    "bottom": "BLACKED red thong panties",
    "shoes": "none" 
  }
)

outfits("lana", "casual",
  {
    "name": "blacked onepiece",
    "flavor": "Bold, daring, and unmistakably BLACKED – make waves everywhere you go!",
    "description": "BLACKED leotard",
    "price": 230, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 7,
    "durability": 8,
    "style": "slutty",
    "tags": ["waterproof","fuckboy magnet","blacked","black magnet"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 4,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "onepiece": "BLACKED leotard",
    "shoes": "none" 
  },
  {
    "name": "blacked jersey",
    "flavor": "The Iconic 23. Inspired by the GOAT, made for legends like you.",
    "description": "BLACKED Jersey",
    "price": 360, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked","black magnet"],
    "colors": ["red","black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "onepiece": "BLACKED red jersey",
    "shoes": "sneakers" 
  },
  {
    "name": "blacked rebel",
    "flavor": "Rebel in style with this BLACKED look.",
    "description": "BLACKED jacket and bodysuit",
    "price": 420, 
    "type": "casual",
    "sluttiness": 10,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["chad magnet","blacked","black magnet"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["cleavage","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["fetish","casual","stylin"],
    "top": "BLACKED cropped faux-leather jacket",
    "bottom": "BLACKED red thong bodysuit with fishnets",
    "shoes": "heeled boots" 
  }
)

outfits("liya", "gym",
  {
    "name": "blacked original",
    "flavor": "Featuring the original BLACKED logo band, this is a sporty look that feels sexy every day.",
    "description": "BLACKED underwear",
    "price": 200, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["workout","chad magnet","blacked","black magnet"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED sports bra",
    "bottom": "BLACKED thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked white",
    "flavor": "The *White* Set. Light, bright, and unmistakably BLACKED.",
    "description": "BLACKED underwear",
    "price": 250, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "slutty",
    "tags": ["great workout","fuckboy magnet","blacked","black magnet"],
    "colors": ["white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED white sports bra",
    "bottom": "BLACKED white thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked red",
    "flavor": "10th anniversary edition! Celebrate in style with this bold BLACKED look.",
    "description": "BLACKED underwear",
    "price": 300, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["great workout","rich magnet","blacked","black magnet"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED red sports bra",
    "bottom": "BLACKED red thong panties",
    "shoes": "none" 
  }
)

outfits("liya", "casual",
  {
    "name": "blacked onepiece",
    "flavor": "Bold, daring, and unmistakably BLACKED – make waves everywhere you go!",
    "description": "BLACKED leotard",
    "price": 230, 
    "type": "casual",
    "sluttiness": 10,
    "comfort": 7,
    "durability": 8,
    "style": "slutty",
    "tags": ["fuckboy magnet","blacked","black magnet","stockings","long changing"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 4,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED leotard",
    "bottom": "fishnet stockings",
    "shoes": "thigh high heeled boots"
  },
  {
    "name": "blacked jersey",
    "flavor": "The Iconic 23. Inspired by the GOAT, made for legends like you.",
    "description": "BLACKED Jersey",
    "price": 360, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked","black magnet"],
    "colors": ["red","black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED red jersey",
    "bottom": "fishnet stockings",
    "shoes": "heeled sneakers" 
  },
  {
    "name": "blacked and white",
    "flavor": "BLACKED and White. The perfect combination.",
    "description": "BLACKED Sporty Outfit",
    "price": 190, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","chad magnet","blacked","black magnet"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "white cropped BLACKED bralette",
    "bottom": "BLACKED thong panties",
    "shoes": "sneakers" 
  }
)

outfits("mia", "gym",
  {
    "name": "blacked original",
    "flavor": "Featuring the original BLACKED logo band, this is a sporty look that feels sexy every day.",
    "description": "BLACKED underwear",
    "price": 200, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["workout","chad magnet","blacked","black magnet"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED sports bra",
    "bottom": "BLACKED thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked white",
    "flavor": "The *White* Set. Light, bright, and unmistakably BLACKED.",
    "description": "BLACKED underwear",
    "price": 250, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "slutty",
    "tags": ["great workout","fuckboy magnet","blacked","black magnet"],
    "colors": ["white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED white sports bra",
    "bottom": "BLACKED white thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked red",
    "flavor": "10th anniversary edition! Celebrate in style with this bold BLACKED look.",
    "description": "BLACKED underwear",
    "price": 300, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["great workout","rich magnet","blacked","black magnet"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED red sports bra",
    "bottom": "BLACKED red thong panties",
    "shoes": "none" 
  }
)

outfits("mia", "beach",
  {
    "name": "blacked onepiece",
    "flavor": "Bold, daring, and unmistakably BLACKED – make waves everywhere you go!",
    "description": "BLACKED Swimsuit",
    "price": 180, 
    "type": "one-piece swimsuit",
    "sluttiness": 6,
    "comfort": 7,
    "durability": 8,
    "style": "sexy",
    "tags": ["waterproof","jock magnet","blacked","black magnet"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 4,
    "locations": ["beach","fetish"],
    "onepiece": "BLACKED swimsuit",
    "shoes": "none" 
  }
)

outfits("mia", "casual",
  {
    "name": "blacked jersey",
    "flavor": "The Iconic 23. Inspired by the GOAT, made for legends like you.",
    "description": "BLACKED Jersey",
    "price": 360, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked","black magnet"],
    "colors": ["red","black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","lots of cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "onepiece": "BLACKED red jersey",
    "shoes": "none" 
  },
  {
    "name": "blacked rebel",
    "flavor": "Rebel in style with this BLACKED look.",
    "description": "BLACKED jacket and bodysuit",
    "price": 420, 
    "type": "casual",
    "sluttiness": 10,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["chad magnet","blacked","black magnet"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["cleavage","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["fetish","casual","stylin"],
    "top": "BLACKED cropped faux-leather jacket",
    "bottom": "BLACKED red thong bodysuit with fishnets",
    "shoes": "heeled boots" 
  }
)

outfits("rae", "gym",
  {
    "name": "blacked original",
    "flavor": "Featuring the original BLACKED logo band, this is a sporty look that feels sexy every day.",
    "description": "BLACKED underwear",
    "price": 200, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["workout","chad magnet","blacked","black magnet"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED sports bra",
    "bottom": "BLACKED thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked white",
    "flavor": "The *White* Set. Light, bright, and unmistakably BLACKED.",
    "description": "BLACKED underwear",
    "price": 250, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "slutty",
    "tags": ["great workout","fuckboy magnet","blacked","black magnet"],
    "colors": ["white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED white sports bra",
    "bottom": "BLACKED white thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked red",
    "flavor": "10th anniversary edition! Celebrate in style with this bold BLACKED look.",
    "description": "BLACKED underwear",
    "price": 300, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["great workout","rich magnet","blacked","black magnet"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED red sports bra",
    "bottom": "BLACKED red thong panties",
    "shoes": "none" 
  }
)

outfits("rae", "casual",
  {
    "name": "blacked onepiece",
    "flavor": "Bold, daring, and unmistakably BLACKED – make waves everywhere you go!",
    "description": "BLACKED leotard",
    "price": 260, 
    "type": "casual",
    "sluttiness": 10,
    "comfort": 7,
    "durability": 8,
    "style": "slutty",
    "tags": ["fuckboy magnet","blacked","black magnet","stockings","long changing"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 4,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED leotard",
    "bottom": "fishnet stockings",
    "shoes": "sneakers"
  },
  {
    "name": "blacked jersey",
    "flavor": "The Iconic 23. Inspired by the GOAT, made for legends like you.",
    "description": "BLACKED Jersey",
    "price": 360, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked","black magnet"],
    "colors": ["red","black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "onepiece": "BLACKED red jersey",
    "shoes": "none" 
  },
  {
    "name": "blacked cutoff",
    "flavor": "Was it already cut like that? or...",
    "description": "BLACKED cutoff",
    "price": 230, 
    "type": "casual",
    "sluttiness": 10,
    "comfort": 6,
    "durability": 8,
    "style": "slutty",
    "tags": ["fuckboy magnet","blacked","black magnet"],
    "colors": ["gray","black"],
    "emphasizes": ["cleavage","boobs"],
    "reveals": ["legs","underboob"],
    "panties under": false,
    "bra under": false,
    "breast support": 2,
    "locations": ["fetish","casual","lounge"],
    "top": "BLACKED cutoff",
    "bottom": "black panties",
    "shoes": "none" 
  }
)

outfits("scarlit", "gym",
  {
    "name": "blacked original",
    "flavor": "Featuring the original BLACKED logo band, this is a sporty look that feels sexy every day.",
    "description": "BLACKED underwear",
    "price": 200, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["workout","chad magnet","blacked","black magnet"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED sports bra",
    "bottom": "BLACKED thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked white",
    "flavor": "The *White* Set. Light, bright, and unmistakably BLACKED.",
    "description": "BLACKED underwear",
    "price": 250, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 8,
    "durability": 8,
    "style": "slutty",
    "tags": ["great workout","fuckboy magnet","blacked","black magnet"],
    "colors": ["white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED white sports bra",
    "bottom": "BLACKED white thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked red",
    "flavor": "10th anniversary edition! Celebrate in style with this bold BLACKED look.",
    "description": "BLACKED underwear",
    "price": 300, 
    "type": "activewear",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 10,
    "style": "slutty",
    "tags": ["great workout","rich magnet","blacked","black magnet"],
    "colors": ["black","red"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "top": "BLACKED red sports bra",
    "bottom": "BLACKED red thong panties",
    "shoes": "none" 
  },
  {
    "name": "blacked yoga",
    "flavor": "Sporty meets stylish. BLACKED brings elegance to every workout.",
    "description": "BLACKED yoga outfit",
    "price": 280, 
    "type": "activewear",
    "sluttiness": 6,
    "comfort": 6,
    "durability": 10,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked","black magnet"],
    "colors": ["black","pink"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["tummy","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 8,
    "locations": ["gym","fetish","casual","lounge"],
    "top": "BLACKED pink sports bra",
    "bottom": "BLACKED pink leggings",
    "shoes": "sneakers" 
  }
)

outfits("scarlit", "casual",
  {
    "name": "blacked onepiece",
    "flavor": "Bold, daring, and unmistakably BLACKED – make waves everywhere you go!",
    "description": "BLACKED leotard",
    "price": 230, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 7,
    "durability": 8,
    "style": "slutty",
    "tags": ["waterproof","fuckboy magnet","blacked","black magnet"],
    "colors": ["black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks","cleavage"],
    "panties under": false,
    "bra under": false,
    "breast support": 4,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "onepiece": "BLACKED leotard",
    "shoes": "none" 
  },
  {
    "name": "blacked jersey",
    "flavor": "The Iconic 23. Inspired by the GOAT, made for legends like you.",
    "description": "BLACKED Jersey",
    "price": 360, 
    "type": "casual",
    "sluttiness": 8,
    "comfort": 6,
    "durability": 8,
    "style": "sexy",
    "tags": ["great workout","jock magnet","blacked","black magnet"],
    "colors": ["red","black","white"],
    "emphasizes": ["cleavage","butt"],
    "reveals": ["legs","asscheeks"],
    "panties under": false,
    "bra under": false,
    "breast support": 6,
    "locations": ["gym","beach","lingerie","fetish","casual","lounge"],
    "onepiece": "BLACKED red jersey",
    "shoes": "none" 
  }
)
