init_character_for_position("ella")

positions("ella", "active", "cowgirl",
    {
        "name": "floppy rider",
        "flavor": "Your floppy tits are...well, floppin' all over the place.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 3,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "grab boobs", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["couch"]
    },
    {
        "name": "impale yourself on BBC",
        "flavor": "It's so big compared to your tiny hole, there really isn't a better way to describe it.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "length",
        "his pleasure": 8,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "butt jiggle", "grab waist"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "let him help",
        "flavor": "You must be going too slow because he insists on helping.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 6,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "grab butt", "spank"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["couch"]
    },
    {
        "name": "make it fit",
        "flavor": "You're determined. Come hell or high water, you're going to make this thing fit.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 6,
        "pleasure factor": "width",
        "his pleasure": 6,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "spank", "butt jiggle", "grab butt"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["bed", "couch"]
    },
    {
        "name": "medium riding",
        "flavor": "You've gotten pretty good at this. You know the right angles.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "boobs jiggle", "grab butt", "butt jiggle", "look back"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "reverse wide stance",
        "flavor": "You straddle his legs and sit down on top of that huge cock.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 5,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "boobs jiggle", "grab waist"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "slide on down",
        "flavor": "A new favorite past time, sliding up and down that pole.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 3,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "grab butt", "spank"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["couch"]
    },
    {
        "name": "slip and slide",
        "flavor": "He might have gone overboard with the massage oil. Everything is so slippery.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 2,
        "roughness": 1,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "boobs jiggle", "balance on chest", "oiled up"],
        "skill": "active sex",
        "skill level": 2,
        "locations": ["couch"]
    },
    {
        "name": "tit smothering twerk",
        "flavor": "You might not even realize it but your tits are smothering him... but that's okay, some people are into that.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "spank", "butt jiggle", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "twerk on that cock",
        "flavor": "The art of twerking is lost on some people. But not you. Who knew you were an artist.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 5,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "butt jiggle", "grab butt"],
        "skill": "active sex",
        "skill level": 6,
        "locations": ["couch"]
    }
);

positions("ella", "active", "doggy",
    {
        "name": "slide it back",
        "flavor": "He might have got things started but you're getting into it now.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 7,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["doggy", "black", "look back", "boobs jiggle", "grab butt"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["couch"]
    }
);

positions("ella", "active", "missionary",
    {
        "name": "rub your clit too",
        "flavor": "You can't help but touch yourself while he pumps.",
        "type": "active",
        "subtype": "missionary",
        "position": "side fuck",
        "athletics": 7,
        "roughness": 5,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["side fuck", "black", "boobs jiggle", "touch yourself", "grab shoulders"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "rubbing and pumping",
        "flavor": "Sometimes it's a two person job. You rub. He pumps.",
        "type": "active",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["missionary", "black", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["couch"]
    }
);

positions("ella", "active", "service",
    {
        "name": "69 tit job",
        "flavor": "It works perfectly. His member gets smothered in between your buttery tits and he gets to taste your fun little snack pack.",
        "type": "active",
        "subtype": "service",
        "position": "69",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "oral",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["69", "close to crotch", "titfuck", "black"],
        "skill": "blowjob",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "cock and balls massage",
        "flavor": "Don't forget to cup the balls.",
        "type": "active",
        "subtype": "service",
        "position": "handjob",
        "athletics": 5,
        "roughness": 2,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["handjob", "close to crotch", "black", "oiled up", "slow"],
        "skill": "handjob",
        "skill level": 3,
        "locations": ["couch"]
    },
    {
        "name": "lick it like a lollipop",
        "flavor": "If you can't even take half of it in your mouth, then you might as well lick it. Yummy.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["blowjob", "close to crotch", "black", "licking"],
        "skill": "blowjob",
        "skill level": 4,
        "locations": ["couch"]
    },
    {
        "name": "sixty-nine",
        "flavor": "You both deserve a little snack break.",
        "type": "active",
        "subtype": "service",
        "position": "69",
        "athletics": 7,
        "roughness": 5,
        "your pleasure": 8,
        "pleasure factor": "oral",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["69", "close to crotch", "licking", "black"],
        "skill": "blowjob",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "tiddy jerk",
        "flavor": "I'm sure your fun bags feel amazing squished against his member.",
        "type": "active",
        "subtype": "service",
        "position": "titfuck",
        "athletics": 7,
        "roughness": 5,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["titfuck", "close to crotch", "black"],
        "skill": "titfuck",
        "skill level": 5,
        "locations": ["bed", "couch"]
    },
    {
        "name": "tit job",
        "flavor": "Jerk him off with your squishy funmellows.",
        "type": "active",
        "subtype": "service",
        "position": "titfuck",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["titfuck", "close to crotch", "black", "sloppy"],
        "skill": "titfuck",
        "skill level": 4,
        "locations": ["couch"]
    },
    {
        "name": "train your gag reflex",
        "flavor": "You're not great at it, but you're trying!",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 4,
        "roughness": 5,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["blowjob", "close to crotch", "black", "deepthroat"],
        "skill": "gag reflex",
        "skill level": 3,
        "locations": ["couch"]
    },
    {
        "name": "worship BBC",
        "flavor": "BBC is your new God. Worship it.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 5,
        "roughness": 3,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["blowjob", "close to crotch", "black", "deepthroat"],
        "skill": "blowjob",
        "skill level": 5,
        "locations": ["couch"]
    }
);

positions("ella", "passive", "cowgirl",
    {
        "name": "drilled",
        "flavor": "What's it feel like to get endlessly drilled by BBC?",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 5,
        "your pleasure": 9,
        "pleasure factor": "length",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "look back", "grab waist", "butt jiggle", "grab butt", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "jiggly blaster",
        "flavor": "Leaning way back, your tits jiggle in the wind with every thrust.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "boobs jiggle", "touch yourself", "grab waist"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "juices flowing",
        "flavor": "He really knows how to get your juices flowing. So creamy.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 8,
        "roughness": 7,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "boobs jiggle", "balls deep", "spank"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "pleasure seeker",
        "flavor": "It's like his dick is launching pleasure seeking missiles, straight into your pussy.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 5,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "boobs jiggle", "hair swish"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "properly pounded",
        "flavor": "You're getting a proper pounding.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 8,
        "roughness": 7,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "boobs jiggle", "grab waist", "eyes roll"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "side saddle",
        "flavor": "Traditionally side saddle was meant for ladies to show dignity and grace while riding... I'm not sure this is what they had in mind.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 7,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "boobs jiggle", "hair swish", "grab butt"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["couch"]
    },
    {
        "name": "take a seat",
        "flavor": "He always takes special care of his favorite ladies, inviting them to take the best seat in the house. *Hint, it's on top of his cock.*",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 5,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "boobs jiggle", "grab butt", "look back"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "taking charge",
        "flavor": "He pulls you close possessively. He's taken charge. You're his now.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "grab waist", "boobs jiggle", "look back", "butt jiggle", "spank"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["bed", "couch"]
    },
    {
        "name": "weapons of mass destruction",
        "flavor": "Do you have a permit for those weapons?",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 6,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["cowgirl", "black", "boobs jiggle", "grab boobs", "reverse cowgirl"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["bed"]
    }
);

positions("ella", "passive", "doggy",
    {
        "name": "face down ass up",
        "flavor": "Go on, take a break. He'll take it from here. Just keep that back arched.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 5,
        "roughness": 4,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["doggy", "black", "ass up"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "invisible chair",
        "flavor": "He's squatting like he's about to sit in a chair, but instead he's pulling you backward into his dick.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 8,
        "roughness": 7,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["doggy", "black", "boobs jiggle", "look back", "grab waist"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "just take it",
        "flavor": "Not a lot you can do about it, so just lay there and take it.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 7,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["doggy", "black", "grab waist", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "tiddy clapping",
        "flavor": "Even your tiddies are impressed with his performance. They're giving him a round of applause.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 7,
        "roughness": 5,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["doggy", "black", "tits clap", "boobs jiggle", "grab waist"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "udderly delightful",
        "flavor": "You can't expect to have tits like this and not catch a stray udder joke every now and then.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 8,
        "roughness": 7,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["doggy", "black", "boobs jiggle", "look back", "grab waist"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["standing"]
    }
);

positions("ella", "passive", "missionary",
    {
        "name": "digging deep",
        "flavor": "Wow, that thing is really long. You're gonna fit that whole thing inside you?",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 8,
        "roughness": 6,
        "your pleasure": 9,
        "pleasure factor": "length",
        "his pleasure": 10,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["missionary", "black", "boobs jiggle", "leg up", "touch yourself"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["couch"]
    },
    {
        "name": "funbag grip test",
        "flavor": "He takes a double handful of your fun bags and gives them a good squeeze.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 7,
        "roughness": 7,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["missionary", "black", "grab boobs", "eye contact", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["bed"]
    },
    {
        "name": "missionary for dummies",
        "flavor": "There's more to it than just laying there.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 5,
        "roughness": 4,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 5,
        "his satisfaction": 5,
        "rhythm": 500,
        "tags": ["missionary", "black", "leg up"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["bed"]
    },
    {
        "name": "one leg up",
        "flavor": "He holds one of your legs up in the air as he plows that pussy from the side.",
        "type": "passive",
        "subtype": "missionary",
        "position": "side fuck",
        "athletics": 7,
        "roughness": 5,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["side fuck", "black", "boobs jiggle", "leg up"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "pretzel fuck",
        "flavor": "He's got you all twisted up. But whatever he's doing, feels great.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 8,
        "roughness": 5,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["missionary", "black", "grab butt", "leg up"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "side pretzel",
        "flavor": "You don't know what it's called, you just don't want him to stop.",
        "type": "passive",
        "subtype": "missionary",
        "position": "side fuck",
        "athletics": 7,
        "roughness": 4,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["side fuck", "black", "boobs jiggle", "kiss", "leg up"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "side pumper",
        "flavor": "Doesn't matter the angle, he's going to keep pumping. You could fall on the floor and he'd still be pumping.",
        "type": "passive",
        "subtype": "missionary",
        "position": "side fuck",
        "athletics": 7,
        "roughness": 7,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["side fuck", "black", "boobs jiggle", "touch yourself", "legs in the air"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "side show",
        "flavor": "Legs off to the side, you're presenting that pussy like it's a prize. His prize, that he's here to claim.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 8,
        "roughness": 6,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["missionary", "black", "boobs jiggle", "eye contact", "legs together"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "so fuckin good",
        "flavor": "There's no other way to describe it. It's just so fuckin' good.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 7,
        "roughness": 6,
        "your pleasure": 10,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["missionary", "black", "legs in the air", "boobs jiggle", "balls deep", "eyes roll"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["bed", "couch"]
    },
    {
        "name": "stretching you out",
        "flavor": "It's just so girthy... he's really doing a number on your ~~tight~~ pussy.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 7,
        "roughness": 6,
        "your pleasure": 7,
        "pleasure factor": "width",
        "his pleasure": 9,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["missionary", "black", "boobs jiggle", "touch yourself", "leg up", "tits rub"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "the right angles",
        "flavor": "It doesn't have to always be hard and fast. If you get the angles right, it feels just as good.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 5,
        "roughness": 4,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["missionary", "black", "leg up", "eyes roll"],
        "skill": "passive sex",
        "skill level": 3,
        "locations": ["couch"]
    }
);

positions("ella", "passive", "service",
    {
        "name": "finger lickin good",
        "flavor": "He slips a finger into your pussy while he flicks your bean with his tongue.",
        "type": "passive",
        "subtype": "service",
        "position": "cunnilingus",
        "athletics": 6,
        "roughness": 5,
        "your pleasure": 9,
        "pleasure factor": "oral",
        "his pleasure": 0,
        "his satisfaction": 0,
        "rhythm": 500,
        "tags": ["licking", "black", "tits rub", "fingering", "sloppy"],
        "skill": "orgasm control",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "tiddy fleshlight",
        "flavor": "Your squishy fun bags make an excellent fleshlight when you hold them around his cock.",
        "type": "passive",
        "subtype": "service",
        "position": "titfuck",
        "athletics": 7,
        "roughness": 5,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["titfuck", "close to crotch", "black"],
        "skill": "titfuck",
        "skill level": 6,
        "locations": ["bed"]
    },
    {
        "name": "titfuck",
        "flavor": "He's actually fucking your tits like a pussy. You better tilt your head back, the head of his cock keeps ramming into your throat.",
        "type": "passive",
        "subtype": "service",
        "position": "titfuck",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 10,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["titfuck", "close to crotch", "black", "big thrusts"],
        "skill": "titfuck",
        "skill level": 7,
        "locations": ["floor"]
    }
);

