init_character_for_position("liya")

positions("liya", "active", "cowgirl",
    {
        "name": "amateur riding",
        "flavor": "Are you sure you know what you're doing?",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 2,
        "roughness": 1,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 5,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "eye contact", "boobs jiggle", "grab arms", "slow"],
        "skill": "active sex",
        "skill level": 2,
        "locations": ["couch", "chair"]
    },
    {
        "name": "deep grind",
        "flavor": "You grind your hips into his, his BBC hollowing you out as you do.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 2,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "balance on chest", "boobs jiggle", "eye contact", "slow", "balls deep"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["floor"]
    },
    {
        "name": "grinding and gyrating",
        "flavor": "You can't get any closer, so you just roll your hips around with him inside.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 5,
        "roughness": 5,
        "your pleasure": 5,
        "pleasure factor": "length",
        "his pleasure": 5,
        "his satisfaction": 5,
        "rhythm": 500,
        "tags": ["black", "grab butt", "boobs jiggle", "balls deep"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["bed", "couch"]
    },
    {
        "name": "reverse riding",
        "flavor": "He's holding you up, but you still struggle to keep your balance.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "reverse cowgirl", "boobs jiggle", "touch yourself", "balance with feet"],
        "skill": "active sex",
        "skill level": 3,
        "locations": ["couch"]
    },
    {
        "name": "both hands full of ass",
        "flavor": "He's obsessed with your badonkadonk! Taking both hands full as he pulls you into him.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 4,
        "roughness": 6,
        "your pleasure": 7,
        "pleasure factor": "length",
        "his pleasure": 7,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "grab butt", "balls deep", "spank"],
        "skill": "active sex",
        "skill level": 4,
        "locations": ["couch"]
    },
    {
        "name": "wide stance",
        "flavor": "You straddle him with a nice wide stance, positioning yourself perfectly to sit on his cock.",
        "type": "active",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "grab waist", "boobs jiggle", "balls deep"],
        "skill": "active sex",
        "skill level": 6,
        "locations": ["couch", "chair"]
    }
);

positions("liya", "active", "doggy",
    {
        "name": "slide it back",
        "flavor": "You just can't help but slide back on his fat cock.",
        "type": "active",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 3,
        "your pleasure": 8,
        "pleasure factor": "width",
        "his pleasure": 7,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "look back", "boobs jiggle"],
        "skill": "active sex",
        "skill level": 5,
        "locations": ["bed", "couch"]
    }
);

positions("liya", "active", "service",
    {
        "name": "black cock servicing",
        "flavor": "You're such a good little BBC whore... aren't you?",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 4,
        "roughness": 3,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "close to crotch"],
        "skill": "blowjob",
        "skill level": 5,
        "locations": ["couch"]
    },
    {
        "name": "cock and ball washer",
        "flavor": "You're his personal cock and ball washer. Get to it.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 4,
        "roughness": 2,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 6,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "licking"],
        "skill": "blowjob",
        "skill level": 5,
        "locations": ["bed", "couch"]
    },
    {
        "name": "two handed blowjob",
        "flavor": "Sometimes it's just better with both hands.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 4,
        "roughness": 3,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "deepthroat"],
        "skill": "blowjob",
        "skill level": 3,
        "locations": ["floor"]
    },
    {
        "name": "worship BBC",
        "flavor": "BBC is your new God. Worship it.",
        "type": "active",
        "subtype": "service",
        "position": "blowjob",
        "athletics": 4,
        "roughness": 3,
        "your pleasure": 0,
        "pleasure factor": "none",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "close to crotch", "blowjob"],
        "skill": "blowjob",
        "skill level": 6,
        "locations": ["bed", "couch"]
    }
);

positions("liya", "passive", "cowgirl",
    {
        "name": "deep in there",
        "flavor": "He's so deep inside you... getting all up in there.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 5,
        "your pleasure": 8,
        "pleasure factor": "length",
        "his pleasure": 8,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "grab waist", "cowgirl", "balls deep"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["couch"]
    },
    {
        "name": "handmade armbinders",
        "flavor": "He takes charge, grabbing and holding you by your arms as he plows into you.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 7,
        "roughness": 8,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "grab arms"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["couch"]
    },
    {
        "name": "light as a feather",
        "flavor": "He lifts you up, tossing you around like a feather.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "standing fuck",
        "athletics": 5,
        "roughness": 8,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "standing", "kiss", "boobs jiggle", "balls deep"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["standing"]
    },
    {
        "name": "slow ride",
        "flavor": "Take it easy.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 3,
        "roughness": 2,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "slow", "boobs jiggle", "grab butt", "eye contact"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["floor"]
    },
    {
        "name": "spread em",
        "flavor": "With your arms forced behind you, you might as well spead your cheeks.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab arms"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "stretching you out",
        "flavor": "His thick cock, pumping into you over and over... he's stretching you out. You won't be the same after this.",
        "type": "passive",
        "subtype": "cowgirl",
        "position": "cowgirl",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "balls deep", "grab arms", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["couch"]
    }
);

positions("liya", "passive", "doggy",
    {
        "name": "bent over a desk",
        "flavor": "He's got you bent over the desk. What's next? The kitchen table?",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 4,
        "roughness": 3,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 6,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "grab waist"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["desk"]
    },
    {
        "name": "do as he says",
        "flavor": "He grabs you by the hair, drags you into the next room, and fucks you in the doorway.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 7,
        "roughness": 7,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 10,
        "rhythm": 500,
        "tags": ["black", "manhandled", "standing", "pull hair"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["standing"]
    },
    {
        "name": "finding the right angle",
        "flavor": "He keeps shifting around, trying to find the right angle. It's kind of distracting.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 7,
        "roughness": 5,
        "your pleasure": 3,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 7,
        "rhythm": 500,
        "tags": ["black", "grab arms", "look back"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "podracing doggy",
        "flavor": "Now *this* is pod racing!",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 6,
        "roughness": 4,
        "your pleasure": 8,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab arms", "grab boobs", "balls deep"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "rough doggystyle",
        "flavor": "He's really giving it to you.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 7,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "look back"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "squatting wheelbarrow",
        "flavor": "Yep, you read that right. He's squatting and you're the wheelbarrow.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 7,
        "roughness": 6,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "helpless", "squat"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "stuffing that pussy",
        "flavor": "Kind of like a Thanksgiving turkey...maybe after he's done with your hole.",
        "type": "passive",
        "subtype": "doggy",
        "position": "doggystyle",
        "athletics": 5,
        "roughness": 5,
        "your pleasure": 5,
        "pleasure factor": "both",
        "his pleasure": 5,
        "his satisfaction": 5,
        "rhythm": 500,
        "tags": ["black", "choke", "lean against you"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    }
);

positions("liya", "passive", "missionary",
    {
        "name": "any place any time",
        "flavor": "Doesn't matter the location, any surface is suitable for fucking.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "eye contact", "leg up", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["table"]
    },
    {
        "name": "any way he wants it",
        "flavor": "...that's the way he needs it.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "touch yourself", "grab boobs"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["bed"]
    },
    {
        "name": "both legs up",
        "flavor": "You're getting used to being on your back. Your legs instinctively lift up and wrap around him.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 7,
        "roughness": 6,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "kiss", "legs in the air"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "in the other room",
        "flavor": "You're going on a trip... to the other room, apparently.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 8,
        "roughness": 8,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "manhandled", "legs in the air", "kiss"],
        "skill": "passive sex",
        "skill level": 7,
        "locations": ["bed"]
    },
    {
        "name": "on the edge",
        "flavor": "He grabs you and pulls you to the edge, so he can reach you better.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 7,
        "roughness": 5,
        "your pleasure": 6,
        "pleasure factor": "both",
        "his pleasure": 7,
        "his satisfaction": 6,
        "rhythm": 500,
        "tags": ["black", "grab waist", "grab boobs"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["couch"]
    },
    {
        "name": "one leg crossed",
        "flavor": "He crossed one of your legs over the other before pinning you down and fucking you. What a fun angle!",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 6,
        "roughness": 6,
        "your pleasure": 9,
        "pleasure factor": "both",
        "his pleasure": 9,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "leg up", "boobs jiggle", "balls deep", "big thrusts"],
        "skill": "passive sex",
        "skill level": 6,
        "locations": ["couch"]
    },
    {
        "name": "one leg up",
        "flavor": "He tosses one of your legs over his shoulder and starts pumping.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 5,
        "roughness": 4,
        "your pleasure": 7,
        "pleasure factor": "both",
        "his pleasure": 8,
        "his satisfaction": 9,
        "rhythm": 500,
        "tags": ["black", "boobs jiggle", "touch yourself", "leg up"],
        "skill": "passive sex",
        "skill level": 4,
        "locations": ["bed"]
    },
    {
        "name": "passionately pounded",
        "flavor": "He's hitting that sweet spot, deep inside of you.",
        "type": "passive",
        "subtype": "missionary",
        "position": "missionary",
        "athletics": 4,
        "roughness": 4,
        "your pleasure": 8,
        "pleasure factor": "length",
        "his pleasure": 7,
        "his satisfaction": 8,
        "rhythm": 500,
        "tags": ["black", "grab boobs", "boobs jiggle"],
        "skill": "passive sex",
        "skill level": 5,
        "locations": ["couch"]
    }
);

positions("liya", "passive", "service",
    {
        "name": "rimmed and thumbed",
        "flavor": "He slips a thumb into your pussy while tonguing your asshole. He doesn't think he's going to stick it in there does he?",
        "type": "passive",
        "subtype": "service",
        "position": "cunnilingus",
        "athletics": 6,
        "roughness": 5,
        "your pleasure": 8,
        "pleasure factor": "oral",
        "his pleasure": 0,
        "his satisfaction": 0,
        "rhythm": 500,
        "tags": ["black", "licking"],
        "skill": "orgasm control",
        "skill level": 5,
        "locations": ["standing"]
    }
);

